package arc.model.eo;

import gen.common.GenLib;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 14 19:03:07 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArcDocumentAttachmentTlImpl
  extends AuditEntityImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    DocumentAttachmentTlPk,
    DocumentAttachDescription,
    LanguagesFk,
    DocumentAttachmentFk,
    CreatedBy,
    CreationDate,
    ModifiedBy,
    ModifiedDate,
    UserDepartmentFk,
    ArcDocumentAttachment;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }

  public static final int DOCUMENTATTACHMENTTLPK = AttributesEnum.DocumentAttachmentTlPk.index();
  public static final int DOCUMENTATTACHDESCRIPTION = AttributesEnum.DocumentAttachDescription.index();
  public static final int LANGUAGESFK = AttributesEnum.LanguagesFk.index();
  public static final int DOCUMENTATTACHMENTFK = AttributesEnum.DocumentAttachmentFk.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
  public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
  public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();
  public static final int ARCDOCUMENTATTACHMENT = AttributesEnum.ArcDocumentAttachment.index();

  /**
   * This is the default constructor (do not remove).
   */
  public ArcDocumentAttachmentTlImpl()
  {
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    return EntityDefImpl.findDefObject("arc.model.eo.ArcDocumentAttachmentTl");
  }

  /**
   * Gets the attribute value for DocumentAttachmentTlPk, using the alias name DocumentAttachmentTlPk.
   * @return the value of DocumentAttachmentTlPk
   */
  public BigDecimal getDocumentAttachmentTlPk()
  {
    return (BigDecimal) getAttributeInternal(DOCUMENTATTACHMENTTLPK);
  }

  /**
   * Sets <code>value</code> as the attribute value for DocumentAttachmentTlPk.
   * @param value value to set the DocumentAttachmentTlPk
   */
  public void setDocumentAttachmentTlPk(BigDecimal value)
  {
    setAttributeInternal(DOCUMENTATTACHMENTTLPK, value);
  }

  /**
   * Gets the attribute value for DocumentAttachDescription, using the alias name DocumentAttachDescription.
   * @return the value of DocumentAttachDescription
   */
  public String getDocumentAttachDescription()
  {
    return (String) getAttributeInternal(DOCUMENTATTACHDESCRIPTION);
  }

  /**
   * Sets <code>value</code> as the attribute value for DocumentAttachDescription.
   * @param value value to set the DocumentAttachDescription
   */
  public void setDocumentAttachDescription(String value)
  {
    setAttributeInternal(DOCUMENTATTACHDESCRIPTION, value);
  }

  /**
   * Gets the attribute value for LanguagesFk, using the alias name LanguagesFk.
   * @return the value of LanguagesFk
   */
  public BigDecimal getLanguagesFk()
  {
    return (BigDecimal) getAttributeInternal(LANGUAGESFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for LanguagesFk.
   * @param value value to set the LanguagesFk
   */
  public void setLanguagesFk(BigDecimal value)
  {
    setAttributeInternal(LANGUAGESFK, value);
  }

  /**
   * Gets the attribute value for DocumentAttachmentFk, using the alias name DocumentAttachmentFk.
   * @return the value of DocumentAttachmentFk
   */
  public BigDecimal getDocumentAttachmentFk()
  {
    return (BigDecimal) getAttributeInternal(DOCUMENTATTACHMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for DocumentAttachmentFk.
   * @param value value to set the DocumentAttachmentFk
   */
  public void setDocumentAttachmentFk(BigDecimal value)
  {
    setAttributeInternal(DOCUMENTATTACHMENTFK, value);
  }

  /**
   * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
   * @return the value of CreatedBy
   */
  public BigDecimal getCreatedBy()
  {
    return (BigDecimal) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreatedBy.
   * @param value value to set the CreatedBy
   */
  public void setCreatedBy(BigDecimal value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CreationDate, using the alias name CreationDate.
   * @return the value of CreationDate
   */
  public Timestamp getCreationDate()
  {
    return (Timestamp) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreationDate.
   * @param value value to set the CreationDate
   */
  public void setCreationDate(Timestamp value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for ModifiedBy, using the alias name ModifiedBy.
   * @return the value of ModifiedBy
   */
  public BigDecimal getModifiedBy()
  {
    return (BigDecimal) getAttributeInternal(MODIFIEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedBy.
   * @param value value to set the ModifiedBy
   */
  public void setModifiedBy(BigDecimal value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
   * @return the value of ModifiedDate
   */
  public Timestamp getModifiedDate()
  {
    return (Timestamp) getAttributeInternal(MODIFIEDDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedDate.
   * @param value value to set the ModifiedDate
   */
  public void setModifiedDate(Timestamp value)
  {
    setAttributeInternal(MODIFIEDDATE, value);
  }

  /**
   * Gets the attribute value for UserDepartmentFk, using the alias name UserDepartmentFk.
   * @return the value of UserDepartmentFk
   */
  public BigDecimal getUserDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for UserDepartmentFk.
   * @param value value to set the UserDepartmentFk
   */
  public void setUserDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(USERDEPARTMENTFK, value);
  }

  /**
   * @return the associated entity ArcDocumentAttachmentImpl.
   */
  public ArcDocumentAttachmentImpl getArcDocumentAttachment()
  {
    return (ArcDocumentAttachmentImpl) getAttributeInternal(ARCDOCUMENTATTACHMENT);
  }

  /**
   * Sets <code>value</code> as the associated entity ArcDocumentAttachmentImpl.
   */
  public void setArcDocumentAttachment(ArcDocumentAttachmentImpl value)
  {
    setAttributeInternal(ARCDOCUMENTATTACHMENT, value);
  }

  /**
   * @param documentAttachmentTlPk key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(BigDecimal documentAttachmentTlPk)
  {
    return new Key(new Object[] { documentAttachmentTlPk });
  }



  protected void doDML(int operation, oracle.jbo.server.TransactionEvent e)
  {
    if ( operation == DML_UPDATE )
    {
    }
    if ( operation != DML_DELETE )
    {
    }
    super.doDML(operation, e);
    
    if ( operation == DML_INSERT )
    {
      BigDecimal pk = GenLib.getPrimaryKeyValue(getDBTransaction(), "ARC_DOCUMENT_ATTACHMENT_TL_SEQ");
      setDocumentAttachmentTlPk(pk);
    }
  }
}

