package arc.model.eo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 09 19:48:08 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArcFilesLockersTlImpl
  extends AuditEntityImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    FilesLockersTlPk,
    FilesLockersName,
    FilesLockersDesc,
    FilesLockersLocation,
    LanguagesFk,
    FilesLockersFk,
    CreatedBy,
    CreationDate,
    ModifiedBy,
    ModifiedDate,
    UserDepartmentFk,
    DisplayDepartmentsFk,
    ArcFilesLockers;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int FILESLOCKERSTLPK = AttributesEnum.FilesLockersTlPk.index();
  public static final int FILESLOCKERSNAME = AttributesEnum.FilesLockersName.index();
  public static final int FILESLOCKERSDESC = AttributesEnum.FilesLockersDesc.index();
  public static final int FILESLOCKERSLOCATION = AttributesEnum.FilesLockersLocation.index();
  public static final int LANGUAGESFK = AttributesEnum.LanguagesFk.index();
  public static final int FILESLOCKERSFK = AttributesEnum.FilesLockersFk.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
  public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
  public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();
  public static final int DISPLAYDEPARTMENTSFK = AttributesEnum.DisplayDepartmentsFk.index();
  public static final int ARCFILESLOCKERS = AttributesEnum.ArcFilesLockers.index();

  /**
   * This is the default constructor (do not remove).
   */
  public ArcFilesLockersTlImpl()
  {
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    return EntityDefImpl.findDefObject("arc.model.eo.ArcFilesLockersTl");
  }


  /**
   * Gets the attribute value for FilesLockersTlPk, using the alias name FilesLockersTlPk.
   * @return the value of FilesLockersTlPk
   */
  public BigDecimal getFilesLockersTlPk()
  {
    return (BigDecimal) getAttributeInternal(FILESLOCKERSTLPK);
  }

  /**
   * Sets <code>value</code> as the attribute value for FilesLockersTlPk.
   * @param value value to set the FilesLockersTlPk
   */
  public void setFilesLockersTlPk(BigDecimal value)
  {
    setAttributeInternal(FILESLOCKERSTLPK, value);
  }

  /**
   * Gets the attribute value for FilesLockersName, using the alias name FilesLockersName.
   * @return the value of FilesLockersName
   */
  public String getFilesLockersName()
  {
    return (String) getAttributeInternal(FILESLOCKERSNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for FilesLockersName.
   * @param value value to set the FilesLockersName
   */
  public void setFilesLockersName(String value)
  {
    setAttributeInternal(FILESLOCKERSNAME, value);
  }

  /**
   * Gets the attribute value for FilesLockersDesc, using the alias name FilesLockersDesc.
   * @return the value of FilesLockersDesc
   */
  public String getFilesLockersDesc()
  {
    return (String) getAttributeInternal(FILESLOCKERSDESC);
  }

  /**
   * Sets <code>value</code> as the attribute value for FilesLockersDesc.
   * @param value value to set the FilesLockersDesc
   */
  public void setFilesLockersDesc(String value)
  {
    setAttributeInternal(FILESLOCKERSDESC, value);
  }

  /**
   * Gets the attribute value for FilesLockersLocation, using the alias name FilesLockersLocation.
   * @return the value of FilesLockersLocation
   */
  public String getFilesLockersLocation()
  {
    return (String) getAttributeInternal(FILESLOCKERSLOCATION);
  }

  /**
   * Sets <code>value</code> as the attribute value for FilesLockersLocation.
   * @param value value to set the FilesLockersLocation
   */
  public void setFilesLockersLocation(String value)
  {
    setAttributeInternal(FILESLOCKERSLOCATION, value);
  }

  /**
   * Gets the attribute value for LanguagesFk, using the alias name LanguagesFk.
   * @return the value of LanguagesFk
   */
  public BigDecimal getLanguagesFk()
  {
    return (BigDecimal) getAttributeInternal(LANGUAGESFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for LanguagesFk.
   * @param value value to set the LanguagesFk
   */
  public void setLanguagesFk(BigDecimal value)
  {
    setAttributeInternal(LANGUAGESFK, value);
  }

  /**
   * Gets the attribute value for FilesLockersFk, using the alias name FilesLockersFk.
   * @return the value of FilesLockersFk
   */
  public BigDecimal getFilesLockersFk()
  {
    return (BigDecimal) getAttributeInternal(FILESLOCKERSFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for FilesLockersFk.
   * @param value value to set the FilesLockersFk
   */
  public void setFilesLockersFk(BigDecimal value)
  {
    setAttributeInternal(FILESLOCKERSFK, value);
  }

  /**
   * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
   * @return the value of CreatedBy
   */
  public BigDecimal getCreatedBy()
  {
    return (BigDecimal) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreatedBy.
   * @param value value to set the CreatedBy
   */
  public void setCreatedBy(BigDecimal value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CreationDate, using the alias name CreationDate.
   * @return the value of CreationDate
   */
  public Timestamp getCreationDate()
  {
    return (Timestamp) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreationDate.
   * @param value value to set the CreationDate
   */
  public void setCreationDate(Timestamp value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for ModifiedBy, using the alias name ModifiedBy.
   * @return the value of ModifiedBy
   */
  public BigDecimal getModifiedBy()
  {
    return (BigDecimal) getAttributeInternal(MODIFIEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedBy.
   * @param value value to set the ModifiedBy
   */
  public void setModifiedBy(BigDecimal value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
   * @return the value of ModifiedDate
   */
  public Timestamp getModifiedDate()
  {
    return (Timestamp) getAttributeInternal(MODIFIEDDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedDate.
   * @param value value to set the ModifiedDate
   */
  public void setModifiedDate(Timestamp value)
  {
    setAttributeInternal(MODIFIEDDATE, value);
  }

  /**
   * Gets the attribute value for UserDepartmentFk, using the alias name UserDepartmentFk.
   * @return the value of UserDepartmentFk
   */
  public BigDecimal getUserDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for UserDepartmentFk.
   * @param value value to set the UserDepartmentFk
   */
  public void setUserDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(USERDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for DisplayDepartmentsFk, using the alias name DisplayDepartmentsFk.
   * @return the value of DisplayDepartmentsFk
   */
  public BigDecimal getDisplayDepartmentsFk()
  {
    return (BigDecimal) getAttributeInternal(DISPLAYDEPARTMENTSFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for DisplayDepartmentsFk.
   * @param value value to set the DisplayDepartmentsFk
   */
  public void setDisplayDepartmentsFk(BigDecimal value)
  {
    setAttributeInternal(DISPLAYDEPARTMENTSFK, value);
  }

  /**
   * @return the associated entity ArcFilesLockersImpl.
   */
  public ArcFilesLockersImpl getArcFilesLockers()
  {
    return (ArcFilesLockersImpl) getAttributeInternal(ARCFILESLOCKERS);
  }

  /**
   * Sets <code>value</code> as the associated entity ArcFilesLockersImpl.
   */
  public void setArcFilesLockers(ArcFilesLockersImpl value)
  {
    setAttributeInternal(ARCFILESLOCKERS, value);
  }


  /**
   * @param filesLockersTlPk key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(BigDecimal filesLockersTlPk)
  {
    return new Key(new Object[] { filesLockersTlPk });
  }

  protected void doDML(int operation, oracle.jbo.server.TransactionEvent e)
  {
    super.doDML(operation, e);

    if ( operation == DML_INSERT )
    {
      BigDecimal pk = gen.common.GenLib.getPrimaryKeyValue(getDBTransaction(), "ARC_FILES_LOCKERS_TL_SEQ");
      setFilesLockersTlPk(pk);
    }
  }

}

