package arc.model.eo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 09 19:47:56 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArcFilesColumnsLockersTlImpl
  extends AuditEntityImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    FilesColumnsLockersTlPk,
    FilesColumnsLockersName,
    LanguagesFk,
    FilesColumnsLockersFk,
    CreatedBy,
    CreationDate,
    ModifiedBy,
    ModifiedDate,
    UserDepartmentFk,
    DisplayFilesLockersFk,
    ArcFilesColumnsLockers;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int FILESCOLUMNSLOCKERSTLPK = AttributesEnum.FilesColumnsLockersTlPk.index();
  public static final int FILESCOLUMNSLOCKERSNAME = AttributesEnum.FilesColumnsLockersName.index();
  public static final int LANGUAGESFK = AttributesEnum.LanguagesFk.index();
  public static final int FILESCOLUMNSLOCKERSFK = AttributesEnum.FilesColumnsLockersFk.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
  public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
  public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();
  public static final int DISPLAYFILESLOCKERSFK = AttributesEnum.DisplayFilesLockersFk.index();
  public static final int ARCFILESCOLUMNSLOCKERS = AttributesEnum.ArcFilesColumnsLockers.index();

  /**
   * This is the default constructor (do not remove).
   */
  public ArcFilesColumnsLockersTlImpl()
  {
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    return EntityDefImpl.findDefObject("arc.model.eo.ArcFilesColumnsLockersTl");
  }


  /**
   * Gets the attribute value for FilesColumnsLockersTlPk, using the alias name FilesColumnsLockersTlPk.
   * @return the value of FilesColumnsLockersTlPk
   */
  public BigDecimal getFilesColumnsLockersTlPk()
  {
    return (BigDecimal) getAttributeInternal(FILESCOLUMNSLOCKERSTLPK);
  }

  /**
   * Sets <code>value</code> as the attribute value for FilesColumnsLockersTlPk.
   * @param value value to set the FilesColumnsLockersTlPk
   */
  public void setFilesColumnsLockersTlPk(BigDecimal value)
  {
    setAttributeInternal(FILESCOLUMNSLOCKERSTLPK, value);
  }

  /**
   * Gets the attribute value for FilesColumnsLockersName, using the alias name FilesColumnsLockersName.
   * @return the value of FilesColumnsLockersName
   */
  public String getFilesColumnsLockersName()
  {
    return (String) getAttributeInternal(FILESCOLUMNSLOCKERSNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for FilesColumnsLockersName.
   * @param value value to set the FilesColumnsLockersName
   */
  public void setFilesColumnsLockersName(String value)
  {
    setAttributeInternal(FILESCOLUMNSLOCKERSNAME, value);
  }

  /**
   * Gets the attribute value for LanguagesFk, using the alias name LanguagesFk.
   * @return the value of LanguagesFk
   */
  public BigDecimal getLanguagesFk()
  {
    return (BigDecimal) getAttributeInternal(LANGUAGESFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for LanguagesFk.
   * @param value value to set the LanguagesFk
   */
  public void setLanguagesFk(BigDecimal value)
  {
    setAttributeInternal(LANGUAGESFK, value);
  }

  /**
   * Gets the attribute value for FilesColumnsLockersFk, using the alias name FilesColumnsLockersFk.
   * @return the value of FilesColumnsLockersFk
   */
  public BigDecimal getFilesColumnsLockersFk()
  {
    return (BigDecimal) getAttributeInternal(FILESCOLUMNSLOCKERSFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for FilesColumnsLockersFk.
   * @param value value to set the FilesColumnsLockersFk
   */
  public void setFilesColumnsLockersFk(BigDecimal value)
  {
    setAttributeInternal(FILESCOLUMNSLOCKERSFK, value);
  }

  /**
   * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
   * @return the value of CreatedBy
   */
  public BigDecimal getCreatedBy()
  {
    return (BigDecimal) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreatedBy.
   * @param value value to set the CreatedBy
   */
  public void setCreatedBy(BigDecimal value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CreationDate, using the alias name CreationDate.
   * @return the value of CreationDate
   */
  public Timestamp getCreationDate()
  {
    return (Timestamp) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreationDate.
   * @param value value to set the CreationDate
   */
  public void setCreationDate(Timestamp value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for ModifiedBy, using the alias name ModifiedBy.
   * @return the value of ModifiedBy
   */
  public BigDecimal getModifiedBy()
  {
    return (BigDecimal) getAttributeInternal(MODIFIEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedBy.
   * @param value value to set the ModifiedBy
   */
  public void setModifiedBy(BigDecimal value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
   * @return the value of ModifiedDate
   */
  public Timestamp getModifiedDate()
  {
    return (Timestamp) getAttributeInternal(MODIFIEDDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedDate.
   * @param value value to set the ModifiedDate
   */
  public void setModifiedDate(Timestamp value)
  {
    setAttributeInternal(MODIFIEDDATE, value);
  }

  /**
   * Gets the attribute value for UserDepartmentFk, using the alias name UserDepartmentFk.
   * @return the value of UserDepartmentFk
   */
  public BigDecimal getUserDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for UserDepartmentFk.
   * @param value value to set the UserDepartmentFk
   */
  public void setUserDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(USERDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for DisplayFilesLockersFk, using the alias name DisplayFilesLockersFk.
   * @return the value of DisplayFilesLockersFk
   */
  public BigDecimal getDisplayFilesLockersFk()
  {
    return (BigDecimal) getAttributeInternal(DISPLAYFILESLOCKERSFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for DisplayFilesLockersFk.
   * @param value value to set the DisplayFilesLockersFk
   */
  public void setDisplayFilesLockersFk(BigDecimal value)
  {
    setAttributeInternal(DISPLAYFILESLOCKERSFK, value);
  }

  /**
   * @return the associated entity ArcFilesColumnsLockersImpl.
   */
  public ArcFilesColumnsLockersImpl getArcFilesColumnsLockers()
  {
    return (ArcFilesColumnsLockersImpl) getAttributeInternal(ARCFILESCOLUMNSLOCKERS);
  }

  /**
   * Sets <code>value</code> as the associated entity ArcFilesColumnsLockersImpl.
   */
  public void setArcFilesColumnsLockers(ArcFilesColumnsLockersImpl value)
  {
    setAttributeInternal(ARCFILESCOLUMNSLOCKERS, value);
  }


  /**
   * @param filesColumnsLockersTlPk key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(BigDecimal filesColumnsLockersTlPk)
  {
    return new Key(new Object[] { filesColumnsLockersTlPk });
  }

  protected void doDML(int operation, oracle.jbo.server.TransactionEvent e)
  {
    super.doDML(operation, e);

    if ( operation == DML_INSERT )
    {
      BigDecimal pk = gen.common.GenLib.getPrimaryKeyValue(getDBTransaction(), "ARC_FILES_COLUMNS_LOCKERS_TL_SEQ");
      setFilesColumnsLockersTlPk(pk);
    }
  }

}

