package arc.model.eo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 09 19:48:04 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArcFilesLockersImpl
  extends AuditEntityImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    FilesLockersPk,
    DepartmentsFk,
    CreatedBy,
    CreationDate,
    ModifiedBy,
    ModifiedDate,
    UserDepartmentFk,
    DisplayFilesLockersName,
    DisplayFilesLockersDesc,
    DisplayFilesLockersLocation,
    ArcFilesColumnsLockers,
    ArcFilesLockersTl;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int FILESLOCKERSPK = AttributesEnum.FilesLockersPk.index();
  public static final int DEPARTMENTSFK = AttributesEnum.DepartmentsFk.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
  public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
  public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();
  public static final int DISPLAYFILESLOCKERSNAME = AttributesEnum.DisplayFilesLockersName.index();
  public static final int DISPLAYFILESLOCKERSDESC = AttributesEnum.DisplayFilesLockersDesc.index();
  public static final int DISPLAYFILESLOCKERSLOCATION = AttributesEnum.DisplayFilesLockersLocation.index();
  public static final int ARCFILESCOLUMNSLOCKERS = AttributesEnum.ArcFilesColumnsLockers.index();
  public static final int ARCFILESLOCKERSTL = AttributesEnum.ArcFilesLockersTl.index();

  /**
   * This is the default constructor (do not remove).
   */
  public ArcFilesLockersImpl()
  {
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    return EntityDefImpl.findDefObject("arc.model.eo.ArcFilesLockers");
  }


  /**
   * Gets the attribute value for FilesLockersPk, using the alias name FilesLockersPk.
   * @return the value of FilesLockersPk
   */
  public BigDecimal getFilesLockersPk()
  {
    return (BigDecimal) getAttributeInternal(FILESLOCKERSPK);
  }

  /**
   * Sets <code>value</code> as the attribute value for FilesLockersPk.
   * @param value value to set the FilesLockersPk
   */
  public void setFilesLockersPk(BigDecimal value)
  {
    setAttributeInternal(FILESLOCKERSPK, value);
  }

  /**
   * Gets the attribute value for DepartmentsFk, using the alias name DepartmentsFk.
   * @return the value of DepartmentsFk
   */
  public BigDecimal getDepartmentsFk()
  {
    return (BigDecimal) getAttributeInternal(DEPARTMENTSFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for DepartmentsFk.
   * @param value value to set the DepartmentsFk
   */
  public void setDepartmentsFk(BigDecimal value)
  {
    setAttributeInternal(DEPARTMENTSFK, value);
  }

  /**
   * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
   * @return the value of CreatedBy
   */
  public BigDecimal getCreatedBy()
  {
    return (BigDecimal) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreatedBy.
   * @param value value to set the CreatedBy
   */
  public void setCreatedBy(BigDecimal value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CreationDate, using the alias name CreationDate.
   * @return the value of CreationDate
   */
  public Timestamp getCreationDate()
  {
    return (Timestamp) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreationDate.
   * @param value value to set the CreationDate
   */
  public void setCreationDate(Timestamp value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for ModifiedBy, using the alias name ModifiedBy.
   * @return the value of ModifiedBy
   */
  public BigDecimal getModifiedBy()
  {
    return (BigDecimal) getAttributeInternal(MODIFIEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedBy.
   * @param value value to set the ModifiedBy
   */
  public void setModifiedBy(BigDecimal value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
   * @return the value of ModifiedDate
   */
  public Timestamp getModifiedDate()
  {
    return (Timestamp) getAttributeInternal(MODIFIEDDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedDate.
   * @param value value to set the ModifiedDate
   */
  public void setModifiedDate(Timestamp value)
  {
    setAttributeInternal(MODIFIEDDATE, value);
  }

  /**
   * Gets the attribute value for UserDepartmentFk, using the alias name UserDepartmentFk.
   * @return the value of UserDepartmentFk
   */
  public BigDecimal getUserDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for UserDepartmentFk.
   * @param value value to set the UserDepartmentFk
   */
  public void setUserDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(USERDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for DisplayFilesLockersName, using the alias name DisplayFilesLockersName.
   * @return the value of DisplayFilesLockersName
   */
  public String getDisplayFilesLockersName()
  {
    return (String) getAttributeInternal(DISPLAYFILESLOCKERSNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for DisplayFilesLockersName.
   * @param value value to set the DisplayFilesLockersName
   */
  public void setDisplayFilesLockersName(String value)
  {
    setAttributeInternal(DISPLAYFILESLOCKERSNAME, value);
  }

  /**
   * Gets the attribute value for DisplayFilesLockersDesc, using the alias name DisplayFilesLockersDesc.
   * @return the value of DisplayFilesLockersDesc
   */
  public String getDisplayFilesLockersDesc()
  {
    return (String) getAttributeInternal(DISPLAYFILESLOCKERSDESC);
  }

  /**
   * Sets <code>value</code> as the attribute value for DisplayFilesLockersDesc.
   * @param value value to set the DisplayFilesLockersDesc
   */
  public void setDisplayFilesLockersDesc(String value)
  {
    setAttributeInternal(DISPLAYFILESLOCKERSDESC, value);
  }

  /**
   * Gets the attribute value for DisplayFilesLockersLocation, using the alias name DisplayFilesLockersLocation.
   * @return the value of DisplayFilesLockersLocation
   */
  public String getDisplayFilesLockersLocation()
  {
    return (String) getAttributeInternal(DISPLAYFILESLOCKERSLOCATION);
  }

  /**
   * Sets <code>value</code> as the attribute value for DisplayFilesLockersLocation.
   * @param value value to set the DisplayFilesLockersLocation
   */
  public void setDisplayFilesLockersLocation(String value)
  {
    setAttributeInternal(DISPLAYFILESLOCKERSLOCATION, value);
  }

  /**
   * @return the associated entity oracle.jbo.RowIterator.
   */
  public RowIterator getArcFilesColumnsLockers()
  {
    return (RowIterator) getAttributeInternal(ARCFILESCOLUMNSLOCKERS);
  }

  /**
   * @return the associated entity oracle.jbo.RowIterator.
   */
  public RowIterator getArcFilesLockersTl()
  {
    return (RowIterator) getAttributeInternal(ARCFILESLOCKERSTL);
  }


  /**
   * @param filesLockersPk key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(BigDecimal filesLockersPk)
  {
    return new Key(new Object[] { filesLockersPk });
  }

  protected void doDML(int operation, oracle.jbo.server.TransactionEvent e)
  {
    super.doDML(operation, e);

    if ( operation == DML_INSERT )
    {
      BigDecimal pk = gen.common.GenLib.getPrimaryKeyValue(getDBTransaction(), "ARC_FILES_LOCKERS_SEQ");
      setFilesLockersPk(pk);
      oracle.jbo.server.EntityDefImpl def = ArcFilesLockersTlImpl.getDefinitionObject();
      java.util.List<Integer> lang = gen.common.GenLib.getActiveDataLanguages(getDBTransaction());
      for (int i = 0; i < lang.size(); i++)
      {
        ArcFilesLockersTlImpl tl = (ArcFilesLockersTlImpl)def.createInstance2(getDBTransaction(), null);
        tl.setLanguagesFk(new BigDecimal(lang.get(i)));
        tl.setFilesLockersName(getDisplayFilesLockersName());
        tl.setFilesLockersDesc(getDisplayFilesLockersDesc());
        tl.setFilesLockersLocation(getDisplayFilesLockersLocation());
        tl.setFilesLockersFk(getFilesLockersPk());
      }
    }
  }


  public void remove()
  {
    gen.common.GenLib.removeTranlationRows(getArcFilesLockersTl());
    super.remove();
  }

}

