package arc.model.eo;

import java.math.BigDecimal;

import java.sql.Date;
import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 20 20:56:56 AST 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArcFilesRCLockPrivImpl
  extends AuditEntityImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    FilesRCLockPrivPk,
    FilesRowsColumnsLockersFk,
    PrivilegeLevelFk,
    DepartmentsFk,
    GroupsFk,
    StartDate,
    EndDate,
    UsersFk,
    CreatedBy,
    CreationDate,
    ModifiedBy,
    ModifiedDate,
    UserDepartmentFk;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }
  public static final int FILESRCLOCKPRIVPK = AttributesEnum.FilesRCLockPrivPk.index();
  public static final int FILESROWSCOLUMNSLOCKERSFK = AttributesEnum.FilesRowsColumnsLockersFk.index();
  public static final int PRIVILEGELEVELFK = AttributesEnum.PrivilegeLevelFk.index();
  public static final int DEPARTMENTSFK = AttributesEnum.DepartmentsFk.index();
  public static final int GROUPSFK = AttributesEnum.GroupsFk.index();
  public static final int STARTDATE = AttributesEnum.StartDate.index();
  public static final int ENDDATE = AttributesEnum.EndDate.index();
  public static final int USERSFK = AttributesEnum.UsersFk.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
  public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
  public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();

  /**
   * This is the default constructor (do not remove).
   */
  public ArcFilesRCLockPrivImpl()
  {
  }

  /**
   * Gets the attribute value for FilesRCLockPrivPk, using the alias name FilesRCLockPrivPk.
   * @return the value of FilesRCLockPrivPk
   */
  public BigDecimal getFilesRCLockPrivPk()
  {
    return (BigDecimal) getAttributeInternal(FILESRCLOCKPRIVPK);
  }

  /**
   * Sets <code>value</code> as the attribute value for FilesRCLockPrivPk.
   * @param value value to set the FilesRCLockPrivPk
   */
  public void setFilesRCLockPrivPk(BigDecimal value)
  {
    setAttributeInternal(FILESRCLOCKPRIVPK, value);
  }

  /**
   * Gets the attribute value for FilesRowsColumnsLockersFk, using the alias name FilesRowsColumnsLockersFk.
   * @return the value of FilesRowsColumnsLockersFk
   */
  public BigDecimal getFilesRowsColumnsLockersFk()
  {
    return (BigDecimal) getAttributeInternal(FILESROWSCOLUMNSLOCKERSFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for FilesRowsColumnsLockersFk.
   * @param value value to set the FilesRowsColumnsLockersFk
   */
  public void setFilesRowsColumnsLockersFk(BigDecimal value)
  {
    setAttributeInternal(FILESROWSCOLUMNSLOCKERSFK, value);
  }

  /**
   * Gets the attribute value for PrivilegeLevelFk, using the alias name PrivilegeLevelFk.
   * @return the value of PrivilegeLevelFk
   */
  public BigDecimal getPrivilegeLevelFk()
  {
    return (BigDecimal) getAttributeInternal(PRIVILEGELEVELFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for PrivilegeLevelFk.
   * @param value value to set the PrivilegeLevelFk
   */
  public void setPrivilegeLevelFk(BigDecimal value)
  {
    setAttributeInternal(PRIVILEGELEVELFK, value);
  }

  /**
   * Gets the attribute value for DepartmentsFk, using the alias name DepartmentsFk.
   * @return the value of DepartmentsFk
   */
  public BigDecimal getDepartmentsFk()
  {
    return (BigDecimal) getAttributeInternal(DEPARTMENTSFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for DepartmentsFk.
   * @param value value to set the DepartmentsFk
   */
  public void setDepartmentsFk(BigDecimal value)
  {
    setAttributeInternal(DEPARTMENTSFK, value);
  }

  /**
   * Gets the attribute value for GroupsFk, using the alias name GroupsFk.
   * @return the value of GroupsFk
   */
  public BigDecimal getGroupsFk()
  {
    return (BigDecimal) getAttributeInternal(GROUPSFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for GroupsFk.
   * @param value value to set the GroupsFk
   */
  public void setGroupsFk(BigDecimal value)
  {
    setAttributeInternal(GROUPSFK, value);
  }

  /**
   * Gets the attribute value for StartDate, using the alias name StartDate.
   * @return the value of StartDate
   */
  public Date getStartDate()
  {
    return (Date) getAttributeInternal(STARTDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for StartDate.
   * @param value value to set the StartDate
   */
  public void setStartDate(Date value)
  {
    setAttributeInternal(STARTDATE, value);
  }

  /**
   * Gets the attribute value for EndDate, using the alias name EndDate.
   * @return the value of EndDate
   */
  public Date getEndDate()
  {
    return (Date) getAttributeInternal(ENDDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for EndDate.
   * @param value value to set the EndDate
   */
  public void setEndDate(Date value)
  {
    setAttributeInternal(ENDDATE, value);
  }

  /**
   * Gets the attribute value for UsersFk, using the alias name UsersFk.
   * @return the value of UsersFk
   */
  public BigDecimal getUsersFk()
  {
    return (BigDecimal) getAttributeInternal(USERSFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for UsersFk.
   * @param value value to set the UsersFk
   */
  public void setUsersFk(BigDecimal value)
  {
    setAttributeInternal(USERSFK, value);
  }

  /**
   * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
   * @return the value of CreatedBy
   */
  public BigDecimal getCreatedBy()
  {
    return (BigDecimal) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreatedBy.
   * @param value value to set the CreatedBy
   */
  public void setCreatedBy(BigDecimal value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CreationDate, using the alias name CreationDate.
   * @return the value of CreationDate
   */
  public Timestamp getCreationDate()
  {
    return (Timestamp) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreationDate.
   * @param value value to set the CreationDate
   */
  public void setCreationDate(Timestamp value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for ModifiedBy, using the alias name ModifiedBy.
   * @return the value of ModifiedBy
   */
  public BigDecimal getModifiedBy()
  {
    return (BigDecimal) getAttributeInternal(MODIFIEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedBy.
   * @param value value to set the ModifiedBy
   */
  public void setModifiedBy(BigDecimal value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
   * @return the value of ModifiedDate
   */
  public Timestamp getModifiedDate()
  {
    return (Timestamp) getAttributeInternal(MODIFIEDDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedDate.
   * @param value value to set the ModifiedDate
   */
  public void setModifiedDate(Timestamp value)
  {
    setAttributeInternal(MODIFIEDDATE, value);
  }

  /**
   * Gets the attribute value for UserDepartmentFk, using the alias name UserDepartmentFk.
   * @return the value of UserDepartmentFk
   */
  public BigDecimal getUserDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for UserDepartmentFk.
   * @param value value to set the UserDepartmentFk
   */
  public void setUserDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(USERDEPARTMENTFK, value);
  }

  /**
   * @param filesRCLockPrivPk key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(BigDecimal filesRCLockPrivPk)
  {
    return new Key(new Object[] { filesRCLockPrivPk });
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    return EntityDefImpl.findDefObject("arc.model.eo.ArcFilesRCLockPriv");
  }

  protected void doDML(int operation, oracle.jbo.server.TransactionEvent e)
  {
    super.doDML(operation, e);

    if ( operation == DML_INSERT )
    {
      BigDecimal pk = gen.common.GenLib.getPrimaryKeyValue(getDBTransaction(), "ARC_FILES_R_C_LOCK_PRIV_SEQ");
      setFilesRCLockPrivPk(pk);
    }
  }

}

