package arc.model.eo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 10 12:09:11 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArcFilesRowsColumnsLockersTlImpl
  extends EntityImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    FilesRowsColumnsLockersTlPk,
    FilesRowsColumnsLockerName,
    LanguagesFk,
    FilesRowsColumnsLockersFk,
    CreatedBy,
    CreationDate,
    ModifiedBy,
    ModifiedDate,
    UserDepartmentFk,
    DisplayFilesColumnsLockersFk,
    ArcFilesRowsColumnsLockers;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int FILESROWSCOLUMNSLOCKERSTLPK = AttributesEnum.FilesRowsColumnsLockersTlPk.index();
  public static final int FILESROWSCOLUMNSLOCKERNAME = AttributesEnum.FilesRowsColumnsLockerName.index();
  public static final int LANGUAGESFK = AttributesEnum.LanguagesFk.index();
  public static final int FILESROWSCOLUMNSLOCKERSFK = AttributesEnum.FilesRowsColumnsLockersFk.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
  public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
  public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();
  public static final int DISPLAYFILESCOLUMNSLOCKERSFK = AttributesEnum.DisplayFilesColumnsLockersFk.index();
  public static final int ARCFILESROWSCOLUMNSLOCKERS = AttributesEnum.ArcFilesRowsColumnsLockers.index();

  /**
   * This is the default constructor (do not remove).
   */
  public ArcFilesRowsColumnsLockersTlImpl()
  {
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    return EntityDefImpl.findDefObject("arc.model.eo.ArcFilesRowsColumnsLockersTl");
  }


  /**
   * Gets the attribute value for FilesRowsColumnsLockersTlPk, using the alias name FilesRowsColumnsLockersTlPk.
   * @return the value of FilesRowsColumnsLockersTlPk
   */
  public BigDecimal getFilesRowsColumnsLockersTlPk()
  {
    return (BigDecimal) getAttributeInternal(FILESROWSCOLUMNSLOCKERSTLPK);
  }

  /**
   * Sets <code>value</code> as the attribute value for FilesRowsColumnsLockersTlPk.
   * @param value value to set the FilesRowsColumnsLockersTlPk
   */
  public void setFilesRowsColumnsLockersTlPk(BigDecimal value)
  {
    setAttributeInternal(FILESROWSCOLUMNSLOCKERSTLPK, value);
  }

  /**
   * Gets the attribute value for FilesRowsColumnsLockerName, using the alias name FilesRowsColumnsLockerName.
   * @return the value of FilesRowsColumnsLockerName
   */
  public String getFilesRowsColumnsLockerName()
  {
    return (String) getAttributeInternal(FILESROWSCOLUMNSLOCKERNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for FilesRowsColumnsLockerName.
   * @param value value to set the FilesRowsColumnsLockerName
   */
  public void setFilesRowsColumnsLockerName(String value)
  {
    setAttributeInternal(FILESROWSCOLUMNSLOCKERNAME, value);
  }

  /**
   * Gets the attribute value for LanguagesFk, using the alias name LanguagesFk.
   * @return the value of LanguagesFk
   */
  public BigDecimal getLanguagesFk()
  {
    return (BigDecimal) getAttributeInternal(LANGUAGESFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for LanguagesFk.
   * @param value value to set the LanguagesFk
   */
  public void setLanguagesFk(BigDecimal value)
  {
    setAttributeInternal(LANGUAGESFK, value);
  }

  /**
   * Gets the attribute value for FilesRowsColumnsLockersFk, using the alias name FilesRowsColumnsLockersFk.
   * @return the value of FilesRowsColumnsLockersFk
   */
  public BigDecimal getFilesRowsColumnsLockersFk()
  {
    return (BigDecimal) getAttributeInternal(FILESROWSCOLUMNSLOCKERSFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for FilesRowsColumnsLockersFk.
   * @param value value to set the FilesRowsColumnsLockersFk
   */
  public void setFilesRowsColumnsLockersFk(BigDecimal value)
  {
    setAttributeInternal(FILESROWSCOLUMNSLOCKERSFK, value);
  }

  /**
   * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
   * @return the value of CreatedBy
   */
  public BigDecimal getCreatedBy()
  {
    return (BigDecimal) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreatedBy.
   * @param value value to set the CreatedBy
   */
  public void setCreatedBy(BigDecimal value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CreationDate, using the alias name CreationDate.
   * @return the value of CreationDate
   */
  public Timestamp getCreationDate()
  {
    return (Timestamp) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreationDate.
   * @param value value to set the CreationDate
   */
  public void setCreationDate(Timestamp value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for ModifiedBy, using the alias name ModifiedBy.
   * @return the value of ModifiedBy
   */
  public BigDecimal getModifiedBy()
  {
    return (BigDecimal) getAttributeInternal(MODIFIEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedBy.
   * @param value value to set the ModifiedBy
   */
  public void setModifiedBy(BigDecimal value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
   * @return the value of ModifiedDate
   */
  public Timestamp getModifiedDate()
  {
    return (Timestamp) getAttributeInternal(MODIFIEDDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedDate.
   * @param value value to set the ModifiedDate
   */
  public void setModifiedDate(Timestamp value)
  {
    setAttributeInternal(MODIFIEDDATE, value);
  }

  /**
   * Gets the attribute value for UserDepartmentFk, using the alias name UserDepartmentFk.
   * @return the value of UserDepartmentFk
   */
  public BigDecimal getUserDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for UserDepartmentFk.
   * @param value value to set the UserDepartmentFk
   */
  public void setUserDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(USERDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for DisplayFilesColumnsLockersFk, using the alias name DisplayFilesColumnsLockersFk.
   * @return the value of DisplayFilesColumnsLockersFk
   */
  public BigDecimal getDisplayFilesColumnsLockersFk()
  {
    return (BigDecimal) getAttributeInternal(DISPLAYFILESCOLUMNSLOCKERSFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for DisplayFilesColumnsLockersFk.
   * @param value value to set the DisplayFilesColumnsLockersFk
   */
  public void setDisplayFilesColumnsLockersFk(BigDecimal value)
  {
    setAttributeInternal(DISPLAYFILESCOLUMNSLOCKERSFK, value);
  }

  /**
   * @return the associated entity ArcFilesRowsColumnsLockersImpl.
   */
  public ArcFilesRowsColumnsLockersImpl getArcFilesRowsColumnsLockers()
  {
    return (ArcFilesRowsColumnsLockersImpl) getAttributeInternal(ARCFILESROWSCOLUMNSLOCKERS);
  }

  /**
   * Sets <code>value</code> as the associated entity ArcFilesRowsColumnsLockersImpl.
   */
  public void setArcFilesRowsColumnsLockers(ArcFilesRowsColumnsLockersImpl value)
  {
    setAttributeInternal(ARCFILESROWSCOLUMNSLOCKERS, value);
  }


  /**
   * @param filesRowsColumnsLockersTlPk key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(BigDecimal filesRowsColumnsLockersTlPk)
  {
    return new Key(new Object[] { filesRowsColumnsLockersTlPk });
  }

  protected void doDML(int operation, oracle.jbo.server.TransactionEvent e)
  {
    super.doDML(operation, e);

    if ( operation == DML_INSERT )
    {
      BigDecimal pk = gen.common.GenLib.getPrimaryKeyValue(getDBTransaction(), "ARC_FILES_ROWS_COLUMNS_LOCKERS_TL_SEQ");
      setFilesRowsColumnsLockersTlPk(pk);
    }
  }
}

