package arc.model.eo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 10 11:59:28 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArcFilesRowsColumnsLockersImpl
  extends EntityImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    FilesRowsColumnsLockersPk,
    FilesColumnsLockersFk,
    CreatedBy,
    CreationDate,
    ModifiedBy,
    ModifiedDate,
    UserDepartmentFk,
    DisplayFilesRowsColumnsLockerName,
    ArcFilesColumnsLockers,
    ArcFilesRowsColumnsLockersTl;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int FILESROWSCOLUMNSLOCKERSPK = AttributesEnum.FilesRowsColumnsLockersPk.index();
  public static final int FILESCOLUMNSLOCKERSFK = AttributesEnum.FilesColumnsLockersFk.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
  public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
  public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();
  public static final int DISPLAYFILESROWSCOLUMNSLOCKERNAME = AttributesEnum.DisplayFilesRowsColumnsLockerName.index();
  public static final int ARCFILESCOLUMNSLOCKERS = AttributesEnum.ArcFilesColumnsLockers.index();
  public static final int ARCFILESROWSCOLUMNSLOCKERSTL = AttributesEnum.ArcFilesRowsColumnsLockersTl.index();

  /**
   * This is the default constructor (do not remove).
   */
  public ArcFilesRowsColumnsLockersImpl()
  {
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    return EntityDefImpl.findDefObject("arc.model.eo.ArcFilesRowsColumnsLockers");
  }


  /**
   * Gets the attribute value for FilesRowsColumnsLockersPk, using the alias name FilesRowsColumnsLockersPk.
   * @return the value of FilesRowsColumnsLockersPk
   */
  public BigDecimal getFilesRowsColumnsLockersPk()
  {
    return (BigDecimal) getAttributeInternal(FILESROWSCOLUMNSLOCKERSPK);
  }

  /**
   * Sets <code>value</code> as the attribute value for FilesRowsColumnsLockersPk.
   * @param value value to set the FilesRowsColumnsLockersPk
   */
  public void setFilesRowsColumnsLockersPk(BigDecimal value)
  {
    setAttributeInternal(FILESROWSCOLUMNSLOCKERSPK, value);
  }

  /**
   * Gets the attribute value for FilesColumnsLockersFk, using the alias name FilesColumnsLockersFk.
   * @return the value of FilesColumnsLockersFk
   */
  public BigDecimal getFilesColumnsLockersFk()
  {
    return (BigDecimal) getAttributeInternal(FILESCOLUMNSLOCKERSFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for FilesColumnsLockersFk.
   * @param value value to set the FilesColumnsLockersFk
   */
  public void setFilesColumnsLockersFk(BigDecimal value)
  {
    setAttributeInternal(FILESCOLUMNSLOCKERSFK, value);
  }

  /**
   * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
   * @return the value of CreatedBy
   */
  public BigDecimal getCreatedBy()
  {
    return (BigDecimal) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreatedBy.
   * @param value value to set the CreatedBy
   */
  public void setCreatedBy(BigDecimal value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CreationDate, using the alias name CreationDate.
   * @return the value of CreationDate
   */
  public Timestamp getCreationDate()
  {
    return (Timestamp) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreationDate.
   * @param value value to set the CreationDate
   */
  public void setCreationDate(Timestamp value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for ModifiedBy, using the alias name ModifiedBy.
   * @return the value of ModifiedBy
   */
  public BigDecimal getModifiedBy()
  {
    return (BigDecimal) getAttributeInternal(MODIFIEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedBy.
   * @param value value to set the ModifiedBy
   */
  public void setModifiedBy(BigDecimal value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
   * @return the value of ModifiedDate
   */
  public Timestamp getModifiedDate()
  {
    return (Timestamp) getAttributeInternal(MODIFIEDDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedDate.
   * @param value value to set the ModifiedDate
   */
  public void setModifiedDate(Timestamp value)
  {
    setAttributeInternal(MODIFIEDDATE, value);
  }

  /**
   * Gets the attribute value for UserDepartmentFk, using the alias name UserDepartmentFk.
   * @return the value of UserDepartmentFk
   */
  public BigDecimal getUserDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for UserDepartmentFk.
   * @param value value to set the UserDepartmentFk
   */
  public void setUserDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(USERDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for DisplayFilesRowsColumnsLockerName, using the alias name DisplayFilesRowsColumnsLockerName.
   * @return the value of DisplayFilesRowsColumnsLockerName
   */
  public String getDisplayFilesRowsColumnsLockerName()
  {
    return (String) getAttributeInternal(DISPLAYFILESROWSCOLUMNSLOCKERNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for DisplayFilesRowsColumnsLockerName.
   * @param value value to set the DisplayFilesRowsColumnsLockerName
   */
  public void setDisplayFilesRowsColumnsLockerName(String value)
  {
    setAttributeInternal(DISPLAYFILESROWSCOLUMNSLOCKERNAME, value);
  }

  /**
   * @return the associated entity ArcFilesColumnsLockersImpl.
   */
  public ArcFilesColumnsLockersImpl getArcFilesColumnsLockers()
  {
    return (ArcFilesColumnsLockersImpl) getAttributeInternal(ARCFILESCOLUMNSLOCKERS);
  }

  /**
   * Sets <code>value</code> as the associated entity ArcFilesColumnsLockersImpl.
   */
  public void setArcFilesColumnsLockers(ArcFilesColumnsLockersImpl value)
  {
    setAttributeInternal(ARCFILESCOLUMNSLOCKERS, value);
  }

  /**
   * @return the associated entity oracle.jbo.RowIterator.
   */
  public RowIterator getArcFilesRowsColumnsLockersTl()
  {
    return (RowIterator) getAttributeInternal(ARCFILESROWSCOLUMNSLOCKERSTL);
  }


  /**
   * @param filesRowsColumnsLockersPk key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(BigDecimal filesRowsColumnsLockersPk)
  {
    return new Key(new Object[] { filesRowsColumnsLockersPk });
  }

  protected void doDML(int operation, oracle.jbo.server.TransactionEvent e)
  {
    super.doDML(operation, e);

    if ( operation == DML_INSERT )
    {
      BigDecimal pk = gen.common.GenLib.getPrimaryKeyValue(getDBTransaction(), "ARC_FILES_ROWS_COLUMNS_LOCKERS_SEQ");
      setFilesRowsColumnsLockersPk(pk);
      oracle.jbo.server.EntityDefImpl def = ArcFilesRowsColumnsLockersTlImpl.getDefinitionObject();
      java.util.List<Integer> lang = gen.common.GenLib.getActiveDataLanguages(getDBTransaction());
      for (int i = 0; i < lang.size(); i++)
      {
        ArcFilesRowsColumnsLockersTlImpl tl = (ArcFilesRowsColumnsLockersTlImpl)def.createInstance2(getDBTransaction(), null);
        tl.setLanguagesFk(new BigDecimal(lang.get(i)));
        tl.setFilesRowsColumnsLockerName(getDisplayFilesRowsColumnsLockerName());
        tl.setFilesRowsColumnsLockersFk(getFilesRowsColumnsLockersPk());
      }
    }
  }


  public void remove()
  {
    gen.common.GenLib.removeTranlationRows(getArcFilesRowsColumnsLockersTl());
    super.remove();
  }
}

