package arc.model.eo;

import com.sd.util.db.DBUtil;

import gen.common.GenLib;

import java.math.BigDecimal;

import java.sql.Timestamp;

import java.util.List;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 16 11:44:22 GMT+02:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArcOldDocumentImpl
  extends AuditEntityImpl
{
  /**
   * Add attribute defaulting logic in this method.
   * @param attributeList list of attribute names/values to initialize the row
   */
  protected void create(AttributeList attributeList)
  {
    super.create(attributeList);
    setOriginalDocumentDisposedFl(new BigDecimal(0));
    setDocYear(GenLib.getCurrentYear()); 
  }

  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    OldDocumentPk,
    DocumentNumber,
    DocumentTypeFk,
    DocumentPriorityFk,
    DocumentSecurityFk,
    FromDepartmentFk,
    ToDepartmentFk,
    DocReceiveDate,
    Room,
    Cupboard,
    Shelve,
    Rack,
    DocExpiryDate,
    Keywords,
    OrgCodeFk,
    CreatedBy,
    CreationDate,
    ModifiedBy,
    ModifiedDate,
    UserDepartmentFk,
    DisposedBy,
    DisposalDate,
    OriginalDocumentDisposedFl,
    DisplayDocumentSubject,
    DisplayDocumentDescription,
    DisplayDocumentComment,
    DisposedCommitteMembers,
    DisposedDecisionDateG,
    DisposedDecisionDateH,
    DisposedDecisionNo,
    EmployeesFk,
    FilesLocationFk,
    DocYear,
    ArcDocumentAttachment,
    ArcOldDocumentTl;
    private static AttributesEnum[] vals = null;
    ;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int DisplayDocumentSubject = AttributesEnum.DisplayDocumentSubject.index();
  public static final int DisplayDocumentComment = AttributesEnum.DisplayDocumentDescription.index();
  public static final int DisplayDocumentDescription = AttributesEnum.DisplayDocumentDescription.index();


  public static final int OLDDOCUMENTPK = AttributesEnum.OldDocumentPk.index();
  public static final int DOCUMENTNUMBER = AttributesEnum.DocumentNumber.index();
  public static final int DOCUMENTTYPEFK = AttributesEnum.DocumentTypeFk.index();
  public static final int DOCUMENTPRIORITYFK = AttributesEnum.DocumentPriorityFk.index();
  public static final int DOCUMENTSECURITYFK = AttributesEnum.DocumentSecurityFk.index();
  public static final int FROMDEPARTMENTFK = AttributesEnum.FromDepartmentFk.index();
  public static final int TODEPARTMENTFK = AttributesEnum.ToDepartmentFk.index();
  public static final int DOCRECEIVEDATE = AttributesEnum.DocReceiveDate.index();
  public static final int ROOM = AttributesEnum.Room.index();
  public static final int CUPBOARD = AttributesEnum.Cupboard.index();
  public static final int SHELVE = AttributesEnum.Shelve.index();
  public static final int RACK = AttributesEnum.Rack.index();
  public static final int DOCEXPIRYDATE = AttributesEnum.DocExpiryDate.index();
  public static final int KEYWORDS = AttributesEnum.Keywords.index();
  public static final int ORGCODEFK = AttributesEnum.OrgCodeFk.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
  public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
  public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();
  public static final int DISPOSEDBY = AttributesEnum.DisposedBy.index();
  public static final int DISPOSALDATE = AttributesEnum.DisposalDate.index();
  public static final int ORIGINALDOCUMENTDISPOSEDFL = AttributesEnum.OriginalDocumentDisposedFl.index();
  public static final int DISPLAYDOCUMENTSUBJECT = AttributesEnum.DisplayDocumentSubject.index();
  public static final int DISPLAYDOCUMENTDESCRIPTION = AttributesEnum.DisplayDocumentDescription.index();
  public static final int DISPLAYDOCUMENTCOMMENT = AttributesEnum.DisplayDocumentComment.index();
  public static final int DISPOSEDCOMMITTEMEMBERS = AttributesEnum.DisposedCommitteMembers.index();
  public static final int DISPOSEDDECISIONDATEG = AttributesEnum.DisposedDecisionDateG.index();
  public static final int DISPOSEDDECISIONDATEH = AttributesEnum.DisposedDecisionDateH.index();
  public static final int DISPOSEDDECISIONNO = AttributesEnum.DisposedDecisionNo.index();
  public static final int EMPLOYEESFK = AttributesEnum.EmployeesFk.index();
  public static final int FILESLOCATIONFK = AttributesEnum.FilesLocationFk.index();
  public static final int DOCYEAR = AttributesEnum.DocYear.index();
  public static final int ARCDOCUMENTATTACHMENT = AttributesEnum.ArcDocumentAttachment.index();
  public static final int ARCOLDDOCUMENTTL = AttributesEnum.ArcOldDocumentTl.index();

  /**
   * This is the default constructor (do not remove).
   */
  public ArcOldDocumentImpl()
  {
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    return EntityDefImpl.findDefObject("arc.model.eo.ArcOldDocument");
  }


  /**
   * Gets the attribute value for OldDocumentPk, using the alias name OldDocumentPk.
   * @return the value of OldDocumentPk
   */
  public BigDecimal getOldDocumentPk()
  {
    return (BigDecimal) getAttributeInternal(OLDDOCUMENTPK);
  }

  /**
   * Sets <code>value</code> as the attribute value for OldDocumentPk.
   * @param value value to set the OldDocumentPk
   */
  public void setOldDocumentPk(BigDecimal value)
  {
    setAttributeInternal(OLDDOCUMENTPK, value);
  }

  /**
   * Gets the attribute value for DocumentNumber, using the alias name DocumentNumber.
   * @return the value of DocumentNumber
   */
  public String getDocumentNumber()
  {
    return (String) getAttributeInternal(DOCUMENTNUMBER);
  }

  /**
   * Sets <code>value</code> as the attribute value for DocumentNumber.
   * @param value value to set the DocumentNumber
   */
  public void setDocumentNumber(String value)
  {
    setAttributeInternal(DOCUMENTNUMBER, value);
  }

  /**
   * Gets the attribute value for DocumentTypeFk, using the alias name DocumentTypeFk.
   * @return the value of DocumentTypeFk
   */
  public BigDecimal getDocumentTypeFk()
  {
    return (BigDecimal) getAttributeInternal(DOCUMENTTYPEFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for DocumentTypeFk.
   * @param value value to set the DocumentTypeFk
   */
  public void setDocumentTypeFk(BigDecimal value)
  {
    setAttributeInternal(DOCUMENTTYPEFK, value);
  }

  /**
   * Gets the attribute value for DocumentPriorityFk, using the alias name DocumentPriorityFk.
   * @return the value of DocumentPriorityFk
   */
  public BigDecimal getDocumentPriorityFk()
  {
    return (BigDecimal) getAttributeInternal(DOCUMENTPRIORITYFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for DocumentPriorityFk.
   * @param value value to set the DocumentPriorityFk
   */
  public void setDocumentPriorityFk(BigDecimal value)
  {
    setAttributeInternal(DOCUMENTPRIORITYFK, value);
  }

  /**
   * Gets the attribute value for DocumentSecurityFk, using the alias name DocumentSecurityFk.
   * @return the value of DocumentSecurityFk
   */
  public BigDecimal getDocumentSecurityFk()
  {
    return (BigDecimal) getAttributeInternal(DOCUMENTSECURITYFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for DocumentSecurityFk.
   * @param value value to set the DocumentSecurityFk
   */
  public void setDocumentSecurityFk(BigDecimal value)
  {
    setAttributeInternal(DOCUMENTSECURITYFK, value);
  }

  /**
   * Gets the attribute value for FromDepartmentFk, using the alias name FromDepartmentFk.
   * @return the value of FromDepartmentFk
   */
  public BigDecimal getFromDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(FROMDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for FromDepartmentFk.
   * @param value value to set the FromDepartmentFk
   */
  public void setFromDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(FROMDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for ToDepartmentFk, using the alias name ToDepartmentFk.
   * @return the value of ToDepartmentFk
   */
  public BigDecimal getToDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(TODEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for ToDepartmentFk.
   * @param value value to set the ToDepartmentFk
   */
  public void setToDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(TODEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for DocReceiveDate, using the alias name DocReceiveDate.
   * @return the value of DocReceiveDate
   */
  public Timestamp getDocReceiveDate()
  {
    return (Timestamp) getAttributeInternal(DOCRECEIVEDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for DocReceiveDate.
   * @param value value to set the DocReceiveDate
   */
  public void setDocReceiveDate(Timestamp value)
  {
    setAttributeInternal(DOCRECEIVEDATE, value);
  }

  /**
   * Gets the attribute value for Room, using the alias name Room.
   * @return the value of Room
   */
  public String getRoom()
  {
    return (String) getAttributeInternal(ROOM);
  }

  /**
   * Sets <code>value</code> as the attribute value for Room.
   * @param value value to set the Room
   */
  public void setRoom(String value)
  {
    setAttributeInternal(ROOM, value);
  }

  /**
   * Gets the attribute value for Cupboard, using the alias name Cupboard.
   * @return the value of Cupboard
   */
  public String getCupboard()
  {
    return (String) getAttributeInternal(CUPBOARD);
  }

  /**
   * Sets <code>value</code> as the attribute value for Cupboard.
   * @param value value to set the Cupboard
   */
  public void setCupboard(String value)
  {
    setAttributeInternal(CUPBOARD, value);
  }

  /**
   * Gets the attribute value for Shelve, using the alias name Shelve.
   * @return the value of Shelve
   */
  public String getShelve()
  {
    return (String) getAttributeInternal(SHELVE);
  }

  /**
   * Sets <code>value</code> as the attribute value for Shelve.
   * @param value value to set the Shelve
   */
  public void setShelve(String value)
  {
    setAttributeInternal(SHELVE, value);
  }

  /**
   * Gets the attribute value for Rack, using the alias name Rack.
   * @return the value of Rack
   */
  public String getRack()
  {
    return (String) getAttributeInternal(RACK);
  }

  /**
   * Sets <code>value</code> as the attribute value for Rack.
   * @param value value to set the Rack
   */
  public void setRack(String value)
  {
    setAttributeInternal(RACK, value);
  }

  /**
   * Gets the attribute value for DocExpiryDate, using the alias name DocExpiryDate.
   * @return the value of DocExpiryDate
   */
  public Timestamp getDocExpiryDate()
  {
    return (Timestamp) getAttributeInternal(DOCEXPIRYDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for DocExpiryDate.
   * @param value value to set the DocExpiryDate
   */
  public void setDocExpiryDate(Timestamp value)
  {
    setAttributeInternal(DOCEXPIRYDATE, value);
  }

  /**
   * Gets the attribute value for Keywords, using the alias name Keywords.
   * @return the value of Keywords
   */
  public String getKeywords()
  {
    return (String) getAttributeInternal(KEYWORDS);
  }

  /**
   * Sets <code>value</code> as the attribute value for Keywords.
   * @param value value to set the Keywords
   */
  public void setKeywords(String value)
  {
    setAttributeInternal(KEYWORDS, value);
  }

  /**
   * Gets the attribute value for OrgCodeFk, using the alias name OrgCodeFk.
   * @return the value of OrgCodeFk
   */
  public BigDecimal getOrgCodeFk()
  {
    return (BigDecimal) getAttributeInternal(ORGCODEFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for OrgCodeFk.
   * @param value value to set the OrgCodeFk
   */
  public void setOrgCodeFk(BigDecimal value)
  {
    setAttributeInternal(ORGCODEFK, value);
  }

  /**
   * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
   * @return the value of CreatedBy
   */
  public BigDecimal getCreatedBy()
  {
    return (BigDecimal) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreatedBy.
   * @param value value to set the CreatedBy
   */
  public void setCreatedBy(BigDecimal value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CreationDate, using the alias name CreationDate.
   * @return the value of CreationDate
   */
  public Timestamp getCreationDate()
  {
    return (Timestamp) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreationDate.
   * @param value value to set the CreationDate
   */
  public void setCreationDate(Timestamp value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for ModifiedBy, using the alias name ModifiedBy.
   * @return the value of ModifiedBy
   */
  public BigDecimal getModifiedBy()
  {
    return (BigDecimal) getAttributeInternal(MODIFIEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedBy.
   * @param value value to set the ModifiedBy
   */
  public void setModifiedBy(BigDecimal value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
   * @return the value of ModifiedDate
   */
  public Timestamp getModifiedDate()
  {
    return (Timestamp) getAttributeInternal(MODIFIEDDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedDate.
   * @param value value to set the ModifiedDate
   */
  public void setModifiedDate(Timestamp value)
  {
    setAttributeInternal(MODIFIEDDATE, value);
  }

  /**
   * Gets the attribute value for UserDepartmentFk, using the alias name UserDepartmentFk.
   * @return the value of UserDepartmentFk
   */
  public BigDecimal getUserDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for UserDepartmentFk.
   * @param value value to set the UserDepartmentFk
   */
  public void setUserDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(USERDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for DisposedBy, using the alias name DisposedBy.
   * @return the value of DisposedBy
   */
  public BigDecimal getDisposedBy()
  {
    return (BigDecimal) getAttributeInternal(DISPOSEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for DisposedBy.
   * @param value value to set the DisposedBy
   */
  public void setDisposedBy(BigDecimal value)
  {
    setAttributeInternal(DISPOSEDBY, value);
  }

  /**
   * Gets the attribute value for DisposalDate, using the alias name DisposalDate.
   * @return the value of DisposalDate
   */
  public Timestamp getDisposalDate()
  {
    return (Timestamp) getAttributeInternal(DISPOSALDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for DisposalDate.
   * @param value value to set the DisposalDate
   */
  public void setDisposalDate(Timestamp value)
  {
    setAttributeInternal(DISPOSALDATE, value);
  }

  /**
   * Gets the attribute value for OriginalDocumentDisposedFl, using the alias name OriginalDocumentDisposedFl.
   * @return the value of OriginalDocumentDisposedFl
   */
  public BigDecimal getOriginalDocumentDisposedFl()
  {
    return (BigDecimal) getAttributeInternal(ORIGINALDOCUMENTDISPOSEDFL);
  }

  /**
   * Sets <code>value</code> as the attribute value for OriginalDocumentDisposedFl.
   * @param value value to set the OriginalDocumentDisposedFl
   */
  public void setOriginalDocumentDisposedFl(BigDecimal value)
  {
    setAttributeInternal(ORIGINALDOCUMENTDISPOSEDFL, value);
  }


  /**
   * Gets the attribute value for a, using the alias name a.
   * @return the value of a
   */
  public String getDisplayDocumentSubject()
  {
    return (String) getAttributeInternal(DisplayDocumentSubject);
  }

  /**
   * Sets <code>value</code> as the attribute value for a.
   * @param value value to set the a
   */
  public void setDisplayDocumentSubject(String value)
  {
    setAttributeInternal(DisplayDocumentSubject, value);
  }


  /**
   * Gets the attribute value for c, using the alias name c.
   * @return the value of c
   */
  public String getDisplayDocumentDescription()
  {
    return (String) getAttributeInternal(DisplayDocumentDescription);
  }

  /**
   * Sets <code>value</code> as the attribute value for c.
   * @param value value to set the c
   */
  public void setDisplayDocumentDescription(String value)
  {
    setAttributeInternal(DisplayDocumentDescription, value);
  }

  /**
   * Gets the attribute value for DisplayDocumentComment, using the alias name DisplayDocumentComment.
   * @return the value of DisplayDocumentComment
   */
  public String getDisplayDocumentComment()
  {
    return (String) getAttributeInternal(DISPLAYDOCUMENTCOMMENT);
  }

  /**
   * Sets <code>value</code> as the attribute value for DisplayDocumentComment.
   * @param value value to set the DisplayDocumentComment
   */
  public void setDisplayDocumentComment(String value)
  {
    setAttributeInternal(DISPLAYDOCUMENTCOMMENT, value);
  }

  /**
   * Gets the attribute value for DisposedCommitteMembers, using the alias name DisposedCommitteMembers.
   * @return the value of DisposedCommitteMembers
   */
  public String getDisposedCommitteMembers()
  {
    return (String) getAttributeInternal(DISPOSEDCOMMITTEMEMBERS);
  }

  /**
   * Sets <code>value</code> as the attribute value for DisposedCommitteMembers.
   * @param value value to set the DisposedCommitteMembers
   */
  public void setDisposedCommitteMembers(String value)
  {
    setAttributeInternal(DISPOSEDCOMMITTEMEMBERS, value);
  }

  /**
   * Gets the attribute value for DisposedDecisionDateG, using the alias name DisposedDecisionDateG.
   * @return the value of DisposedDecisionDateG
   */
  public Timestamp getDisposedDecisionDateG()
  {
    return (Timestamp) getAttributeInternal(DISPOSEDDECISIONDATEG);
  }

  /**
   * Sets <code>value</code> as the attribute value for DisposedDecisionDateG.
   * @param value value to set the DisposedDecisionDateG
   */
  public void setDisposedDecisionDateG(Timestamp value)
  {
    setAttributeInternal(DISPOSEDDECISIONDATEG, value);
  }

  /**
   * Gets the attribute value for DisposedDecisionDateH, using the alias name DisposedDecisionDateH.
   * @return the value of DisposedDecisionDateH
   */
  public BigDecimal getDisposedDecisionDateH()
  {
    return (BigDecimal) getAttributeInternal(DISPOSEDDECISIONDATEH);
  }

  /**
   * Sets <code>value</code> as the attribute value for DisposedDecisionDateH.
   * @param value value to set the DisposedDecisionDateH
   */
  public void setDisposedDecisionDateH(BigDecimal value)
  {
    setAttributeInternal(DISPOSEDDECISIONDATEH, value);
  }

  /**
   * Gets the attribute value for DisposedDecisionNo, using the alias name DisposedDecisionNo.
   * @return the value of DisposedDecisionNo
   */
  public BigDecimal getDisposedDecisionNo()
  {
    return (BigDecimal) getAttributeInternal(DISPOSEDDECISIONNO);
  }

  /**
   * Sets <code>value</code> as the attribute value for DisposedDecisionNo.
   * @param value value to set the DisposedDecisionNo
   */
  public void setDisposedDecisionNo(BigDecimal value)
  {
    setAttributeInternal(DISPOSEDDECISIONNO, value);
  }

  /**
   * Gets the attribute value for EmployeesFk, using the alias name EmployeesFk.
   * @return the value of EmployeesFk
   */
  public BigDecimal getEmployeesFk()
  {
    return (BigDecimal) getAttributeInternal(EMPLOYEESFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for EmployeesFk.
   * @param value value to set the EmployeesFk
   */
  public void setEmployeesFk(BigDecimal value)
  {
    setAttributeInternal(EMPLOYEESFK, value);
  }

  /**
   * Gets the attribute value for FilesLocationFk, using the alias name FilesLocationFk.
   * @return the value of FilesLocationFk
   */
  public BigDecimal getFilesLocationFk()
  {
    return (BigDecimal) getAttributeInternal(FILESLOCATIONFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for FilesLocationFk.
   * @param value value to set the FilesLocationFk
   */
  public void setFilesLocationFk(BigDecimal value)
  {
    setAttributeInternal(FILESLOCATIONFK, value);
  }

  /**
   * Gets the attribute value for DocYear, using the alias name DocYear.
   * @return the value of DocYear
   */
  public BigDecimal getDocYear()
  {
    return (BigDecimal) getAttributeInternal(DOCYEAR);
  }

  /**
   * Sets <code>value</code> as the attribute value for DocYear.
   * @param value value to set the DocYear
   */
  public void setDocYear(BigDecimal value)
  {
    setAttributeInternal(DOCYEAR, value);
  }


  /**
   * @return the associated entity oracle.jbo.RowIterator.
   */
  public RowIterator getArcDocumentAttachment()
  {
    return (RowIterator) getAttributeInternal(ARCDOCUMENTATTACHMENT);
  }

  /**
   * @return the associated entity oracle.jbo.RowIterator.
   */
  public RowIterator getArcOldDocumentTl()
  {
    return (RowIterator) getAttributeInternal(ARCOLDDOCUMENTTL);
  }


  /**
   * @param oldDocumentPk key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(BigDecimal oldDocumentPk)
  {
    return new Key(new Object[] { oldDocumentPk });
  }

  protected synchronized void doDML(int operation, oracle.jbo.server.TransactionEvent e)
  { 
    if ( operation == DML_UPDATE )
    {
    }
    
    if ( operation != DML_DELETE )
    {
      if(getFromDepartmentFk() == null)
      {
        setFromDepartmentFk(GenLib.getUserLoginDepartment());
      }
    }   
    
    super.doDML(operation, e);
    
    if ( operation == DML_INSERT )
    {
      BigDecimal pk = GenLib.getPrimaryKeyValue(getDBTransaction(), "ARC_OLD_DOCUMENT_SEQ");
      setOldDocumentPk(pk);
     
      EntityDefImpl def = ArcOldDocumentTlImpl.getDefinitionObject();
      
      try
      {
        List<Integer> lang = GenLib.getActiveDataLanguages(getDBTransaction());
        
        for (int i = 0; i < lang.size(); i++)
        {
          ArcOldDocumentTlImpl tl = (ArcOldDocumentTlImpl)def.createInstance2(getDBTransaction(), null);
          tl.setOldDocumentFk(getOldDocumentPk());
          tl.setLanguagesFk(new BigDecimal(lang.get(i)));
          tl.setDocumentSubject(getDisplayDocumentSubject());
          tl.setDocumentDescription(getDisplayDocumentDescription());
          tl.setDocumentComment(getDisplayDocumentComment());
        }
      }
      catch (Exception f)
      {
        f.printStackTrace();
      }
    
    }    
    
  }

  @Override
  public void remove()
  {
    GenLib.removeTranlationRows(getArcOldDocumentTl());  
    super.remove();
  }

//  protected void doDML(int operation, oracle.jbo.server.TransactionEvent e)
//  {
//    super.doDML(operation, e);
//
//    if ( operation == DML_INSERT )
//    {
//      BigDecimal pk = gen.common.GenLib.getPrimaryKeyValue(getDBTransaction(), "ARC_OLD_DOCUMENT_SEQ");
//      setOldDocumentPk(pk);
//      oracle.jbo.server.EntityDefImpl def = ArcOldDocumentTlImpl.getDefinitionObject();
//      java.util.List<Integer> lang = gen.common.GenLib.getActiveDataLanguages(getDBTransaction());
//      for (int i = 0; i < lang.size(); i++)
//      {
//        ArcOldDocumentTlImpl tl = (ArcOldDocumentTlImpl)def.createInstance2(getDBTransaction(), null);
//        tl.setLanguagesFk(new BigDecimal(lang.get(i)));
//        tl.setDocumentSubject(getDisplayDocumentSubject());
//        tl.setDocumentComment(getDisplayDocumentComment());
//        tl.setDocumentDescription(getDisplayDocumentDescription());
//        tl.setOldDocumentFk(getOldDocumentPk());
//      }
//    }
//  }

}
