package arc.model.eo;

import gen.common.GenLib;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 14 19:03:16 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArcOldDocumentTlImpl
  extends AuditEntityImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    OldDocumentTlPk,
    DocumentSubject,
    DocumentComment,
    DocumentDescription,
    LanguagesFk,
    OldDocumentFk,
    CreatedBy,
    CreationDate,
    ModifiedBy,
    ModifiedDate,
    UserDepartmentFk,
    ArcOldDocument;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }

  public static final int OLDDOCUMENTTLPK = AttributesEnum.OldDocumentTlPk.index();
  public static final int DOCUMENTSUBJECT = AttributesEnum.DocumentSubject.index();
  public static final int DOCUMENTCOMMENT = AttributesEnum.DocumentComment.index();
  public static final int DOCUMENTDESCRIPTION = AttributesEnum.DocumentDescription.index();
  public static final int LANGUAGESFK = AttributesEnum.LanguagesFk.index();
  public static final int OLDDOCUMENTFK = AttributesEnum.OldDocumentFk.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
  public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
  public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();
  public static final int ARCOLDDOCUMENT = AttributesEnum.ArcOldDocument.index();

  /**
   * This is the default constructor (do not remove).
   */
  public ArcOldDocumentTlImpl()
  {
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    return EntityDefImpl.findDefObject("arc.model.eo.ArcOldDocumentTl");
  }

  /**
   * Gets the attribute value for OldDocumentTlPk, using the alias name OldDocumentTlPk.
   * @return the value of OldDocumentTlPk
   */
  public BigDecimal getOldDocumentTlPk()
  {
    return (BigDecimal) getAttributeInternal(OLDDOCUMENTTLPK);
  }

  /**
   * Sets <code>value</code> as the attribute value for OldDocumentTlPk.
   * @param value value to set the OldDocumentTlPk
   */
  public void setOldDocumentTlPk(BigDecimal value)
  {
    setAttributeInternal(OLDDOCUMENTTLPK, value);
  }

  /**
   * Gets the attribute value for DocumentSubject, using the alias name DocumentSubject.
   * @return the value of DocumentSubject
   */
  public String getDocumentSubject()
  {
    return (String) getAttributeInternal(DOCUMENTSUBJECT);
  }

  /**
   * Sets <code>value</code> as the attribute value for DocumentSubject.
   * @param value value to set the DocumentSubject
   */
  public void setDocumentSubject(String value)
  {
    setAttributeInternal(DOCUMENTSUBJECT, value);
  }

  /**
   * Gets the attribute value for DocumentComment, using the alias name DocumentComment.
   * @return the value of DocumentComment
   */
  public String getDocumentComment()
  {
    return (String) getAttributeInternal(DOCUMENTCOMMENT);
  }

  /**
   * Sets <code>value</code> as the attribute value for DocumentComment.
   * @param value value to set the DocumentComment
   */
  public void setDocumentComment(String value)
  {
    setAttributeInternal(DOCUMENTCOMMENT, value);
  }

  /**
   * Gets the attribute value for DocumentDescription, using the alias name DocumentDescription.
   * @return the value of DocumentDescription
   */
  public String getDocumentDescription()
  {
    return (String) getAttributeInternal(DOCUMENTDESCRIPTION);
  }

  /**
   * Sets <code>value</code> as the attribute value for DocumentDescription.
   * @param value value to set the DocumentDescription
   */
  public void setDocumentDescription(String value)
  {
    setAttributeInternal(DOCUMENTDESCRIPTION, value);
  }

  /**
   * Gets the attribute value for LanguagesFk, using the alias name LanguagesFk.
   * @return the value of LanguagesFk
   */
  public BigDecimal getLanguagesFk()
  {
    return (BigDecimal) getAttributeInternal(LANGUAGESFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for LanguagesFk.
   * @param value value to set the LanguagesFk
   */
  public void setLanguagesFk(BigDecimal value)
  {
    setAttributeInternal(LANGUAGESFK, value);
  }

  /**
   * Gets the attribute value for OldDocumentFk, using the alias name OldDocumentFk.
   * @return the value of OldDocumentFk
   */
  public BigDecimal getOldDocumentFk()
  {
    return (BigDecimal) getAttributeInternal(OLDDOCUMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for OldDocumentFk.
   * @param value value to set the OldDocumentFk
   */
  public void setOldDocumentFk(BigDecimal value)
  {
    setAttributeInternal(OLDDOCUMENTFK, value);
  }

  /**
   * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
   * @return the value of CreatedBy
   */
  public BigDecimal getCreatedBy()
  {
    return (BigDecimal) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreatedBy.
   * @param value value to set the CreatedBy
   */
  public void setCreatedBy(BigDecimal value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CreationDate, using the alias name CreationDate.
   * @return the value of CreationDate
   */
  public Timestamp getCreationDate()
  {
    return (Timestamp) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreationDate.
   * @param value value to set the CreationDate
   */
  public void setCreationDate(Timestamp value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for ModifiedBy, using the alias name ModifiedBy.
   * @return the value of ModifiedBy
   */
  public BigDecimal getModifiedBy()
  {
    return (BigDecimal) getAttributeInternal(MODIFIEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedBy.
   * @param value value to set the ModifiedBy
   */
  public void setModifiedBy(BigDecimal value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
   * @return the value of ModifiedDate
   */
  public Timestamp getModifiedDate()
  {
    return (Timestamp) getAttributeInternal(MODIFIEDDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedDate.
   * @param value value to set the ModifiedDate
   */
  public void setModifiedDate(Timestamp value)
  {
    setAttributeInternal(MODIFIEDDATE, value);
  }

  /**
   * Gets the attribute value for UserDepartmentFk, using the alias name UserDepartmentFk.
   * @return the value of UserDepartmentFk
   */
  public BigDecimal getUserDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for UserDepartmentFk.
   * @param value value to set the UserDepartmentFk
   */
  public void setUserDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(USERDEPARTMENTFK, value);
  }

  /**
   * @return the associated entity ArcOldDocumentImpl.
   */
  public ArcOldDocumentImpl getArcOldDocument()
  {
    return (ArcOldDocumentImpl) getAttributeInternal(ARCOLDDOCUMENT);
  }

  /**
   * Sets <code>value</code> as the associated entity ArcOldDocumentImpl.
   */
  public void setArcOldDocument(ArcOldDocumentImpl value)
  {
    setAttributeInternal(ARCOLDDOCUMENT, value);
  }

  /**
   * @param oldDocumentTlPk key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(BigDecimal oldDocumentTlPk)
  {
    return new Key(new Object[] { oldDocumentTlPk });
  }



  protected synchronized void doDML(int operation, oracle.jbo.server.TransactionEvent e)
  {
    if ( operation == DML_UPDATE )
    {
    }
    if ( operation != DML_DELETE )
    {
    }
    super.doDML(operation, e);
    
    if ( operation == DML_INSERT )
    {
      BigDecimal pk = GenLib.getPrimaryKeyValue(getDBTransaction(), "ARC_OLD_DOCUMENT_TL_SEQ");
      setOldDocumentTlPk(pk);
    }
  }

//  protected void doDML(int operation, oracle.jbo.server.TransactionEvent e)
//  {
//    super.doDML(operation, e);
//
//    if ( operation == DML_INSERT )
//    {
//      BigDecimal pk = gen.common.GenLib.getPrimaryKeyValue(getDBTransaction(), "ARC_OLD_DOCUMENT_TL_SEQ");
//      setOldDocumentTlPk(pk);
//    }
//  }

}

