package arc.model;


import arc.model.ro.ArcClassificationPVOImpl;
import arc.model.ro.ArcFileLocationDepartmentDetailRVOImpl;
import arc.model.ro.ArcFileLocationWithNoDocumentRVOImpl;
import arc.model.ro.ArcFilesLocationDepartmentMasterRVOImpl;
import arc.model.ro.ArcFilesLocationDepartmentRVOImpl;
import arc.model.ro.ArcFilesLocationDetailRVOImpl;
import arc.model.ro.ArcFilesLocationMasterRVOImpl;

import arc.model.ro.ArcOldDocumentDashboardRVOImpl;
import arc.model.ro.SsoUsersRVOImpl;

import gen.common.BaseAppModuleImpl;


import gen.common.BaseViewObjectImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 14 19:03:19 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl
  extends BaseAppModuleImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public AppModuleImpl()
  {
  }

  /**
   * Container's getter for ArcDocumentAttachmentTlView1.
   * @return ArcDocumentAttachmentTlView1
   */
  public ViewObjectImpl getArcDocumentAttachmentTlView1()
  {
    return (ViewObjectImpl) findViewObject("ArcDocumentAttachmentTlView1");
  }

  /**
   * Container's getter for ArcDocumentAttachmentView1.
   * @return ArcDocumentAttachmentView1
   */
  public ViewObjectImpl getArcDocumentAttachmentView1()
  {
    return (ViewObjectImpl) findViewObject("ArcDocumentAttachmentView1");
  }

  /**
   * Container's getter for ArcOldDocumentTlView1.
   * @return ArcOldDocumentTlView1
   */
  public ViewObjectImpl getArcOldDocumentTlView1()
  {
    return (ViewObjectImpl) findViewObject("ArcOldDocumentTlView1");
  }

  /**
   * Container's getter for ArcOldDocumentView1.
   * @return ArcOldDocumentView1
   */
  public ViewObjectImpl getArcOldDocumentView1()
  {
    return (ViewObjectImpl) findViewObject("ArcOldDocumentView1");
  }

  /**
   * Container's getter for ArcDocumentAttachmentTlView2.
   * @return ArcDocumentAttachmentTlView2
   */
  public ViewObjectImpl getArcDocumentAttachmentTlView2()
  {
    return (ViewObjectImpl) findViewObject("ArcDocumentAttachmentTlView2");
  }

  /**
   * Container's getter for ArcDocumentAttachmentView2.
   * @return ArcDocumentAttachmentView2
   */
  public ViewObjectImpl getArcDocumentAttachmentView2()
  {
    return (ViewObjectImpl) findViewObject("ArcDocumentAttachmentView2");
  }

  /**
   * Container's getter for ArcOldDocumentTlView2.
   * @return ArcOldDocumentTlView2
   */
  public ViewObjectImpl getArcOldDocumentTlView2()
  {
    return (ViewObjectImpl) findViewObject("ArcOldDocumentTlView2");
  }

  /**
   * Container's getter for ArcDocumentAttachmentTlFkLink1.
   * @return ArcDocumentAttachmentTlFkLink1
   */
  public ViewLinkImpl getArcDocumentAttachmentTlFkLink1()
  {
    return (ViewLinkImpl) findViewLink("ArcDocumentAttachmentTlFkLink1");
  }

  /**
   * Container's getter for ArcDocumentAttachmentFkLink1.
   * @return ArcDocumentAttachmentFkLink1
   */
  public ViewLinkImpl getArcDocumentAttachmentFkLink1()
  {
    return (ViewLinkImpl) findViewLink("ArcDocumentAttachmentFkLink1");
  }

  /**
   * Container's getter for ArcDocumentTlFkLink1.
   * @return ArcDocumentTlFkLink1
   */
  public ViewLinkImpl getArcDocumentTlFkLink1()
  {
    return (ViewLinkImpl) findViewLink("ArcDocumentTlFkLink1");
  }

  /**
   * Container's getter for SsoActiveLookupValuesVwView1.
   * @return SsoActiveLookupValuesVwView1
   */
  public ViewObjectImpl getSsoActiveLookupValuesVwView1()
  {
    return (ViewObjectImpl) findViewObject("SsoActiveLookupValuesVwView1");
  }

  /**
   * Container's getter for SsoLanguagesVwView1.
   * @return SsoLanguagesVwView1
   */
  public ViewObjectImpl getSsoLanguagesVwView1()
  {
    return (ViewObjectImpl) findViewObject("SsoLanguagesVwView1");
  }

  /**
   * Container's getter for HcmDepartmentsVwView1.
   * @return HcmDepartmentsVwView1
   */
  public ViewObjectImpl getHcmDepartmentsVwView1()
  {
    return (ViewObjectImpl) findViewObject("HcmDepartmentsVwView1");
  }

  /**
   * Container's getter for ArcDocumentAttachmentTlView3.
   * @return ArcDocumentAttachmentTlView3
   */
  public ViewObjectImpl getArcDocumentAttachmentTlView3()
  {
    return (ViewObjectImpl) findViewObject("ArcDocumentAttachmentTlView3");
  }

  /**
   * Container's getter for ArcDocumentAttachmentTlFkLink2.
   * @return ArcDocumentAttachmentTlFkLink2
   */
  public ViewLinkImpl getArcDocumentAttachmentTlFkLink2()
  {
    return (ViewLinkImpl) findViewLink("ArcDocumentAttachmentTlFkLink2");
  }

  /**
   * Container's getter for ArcAuditModificationsView1.
   * @return ArcAuditModificationsView1
   */
  public ViewObjectImpl getArcAuditModificationsView1()
  {
    return (ViewObjectImpl) findViewObject("ArcAuditModificationsView1");
  }

  /**
   * Container's getter for ReportParametersRVO1.
   * @return ReportParametersRVO1
   */
  public ViewObjectImpl getReportParametersRVO1()
  {
    return (ViewObjectImpl) findViewObject("ReportParametersRVO1");
  }

  /**
   * Container's getter for ArcClassificationPVO1.
   * @return ArcClassificationPVO1
   */
  public ArcClassificationPVOImpl getArcClassificationPVO1()
  {
    return (ArcClassificationPVOImpl) findViewObject("ArcClassificationPVO1");
  }

  /**
   * Container's getter for ArcFilesLocationTlView1.
   * @return ArcFilesLocationTlView1
   */
  public ViewObjectImpl getArcFilesLocationTlView1()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesLocationTlView1");
  }

  /**
   * Container's getter for ArcFilesLocationView1.
   * @return ArcFilesLocationView1
   */
  public ViewObjectImpl getArcFilesLocationView1()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesLocationView1");
  }

  /**
   * Container's getter for ArcFlStandardsTlView1.
   * @return ArcFlStandardsTlView1
   */
  public ViewObjectImpl getArcFlStandardsTlView1()
  {
    return (ViewObjectImpl) findViewObject("ArcFlStandardsTlView1");
  }

  /**
   * Container's getter for ArcFlStandardsView1.
   * @return ArcFlStandardsView1
   */
  public ViewObjectImpl getArcFlStandardsView1()
  {
    return (ViewObjectImpl) findViewObject("ArcFlStandardsView1");
  }

  /**
   * Container's getter for ArcFlsLocationsTlView1.
   * @return ArcFlsLocationsTlView1
   */
  public ViewObjectImpl getArcFlsLocationsTlView1()
  {
    return (ViewObjectImpl) findViewObject("ArcFlsLocationsTlView1");
  }

  /**
   * Container's getter for ArcFlsLocationsView1.
   * @return ArcFlsLocationsView1
   */
  public ViewObjectImpl getArcFlsLocationsView1()
  {
    return (ViewObjectImpl) findViewObject("ArcFlsLocationsView1");
  }

  /**
   * Container's getter for ArcFilesLocationView2.
   * @return ArcFilesLocationView2
   */
  public ViewObjectImpl getArcFilesLocationView2()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesLocationView2");
  }

  /**
   * Container's getter for ArcFilesLocationTlView2.
   * @return ArcFilesLocationTlView2
   */
  public ViewObjectImpl getArcFilesLocationTlView2()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesLocationTlView2");
  }

  /**
   * Container's getter for ArcFlsLocationsView2.
   * @return ArcFlsLocationsView2
   */
  public ViewObjectImpl getArcFlsLocationsView2()
  {
    return (ViewObjectImpl) findViewObject("ArcFlsLocationsView2");
  }

  /**
   * Container's getter for ArcFlsLocationsTlView2.
   * @return ArcFlsLocationsTlView2
   */
  public ViewObjectImpl getArcFlsLocationsTlView2()
  {
    return (ViewObjectImpl) findViewObject("ArcFlsLocationsTlView2");
  }

  /**
   * Container's getter for ArcFlsLocationsView3.
   * @return ArcFlsLocationsView3
   */
  public ViewObjectImpl getArcFlsLocationsView3()
  {
    return (ViewObjectImpl) findViewObject("ArcFlsLocationsView3");
  }

  /**
   * Container's getter for ArcFlStandardsTlView2.
   * @return ArcFlStandardsTlView2
   */
  public ViewObjectImpl getArcFlStandardsTlView2()
  {
    return (ViewObjectImpl) findViewObject("ArcFlStandardsTlView2");
  }

  /**
   * Container's getter for ArcFilesLocationFk1Link1.
   * @return ArcFilesLocationFk1Link1
   */
  public ViewLinkImpl getArcFilesLocationFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("ArcFilesLocationFk1Link1");
  }

  /**
   * Container's getter for ArcFilesLocationTlFk1Link1.
   * @return ArcFilesLocationTlFk1Link1
   */
  public ViewLinkImpl getArcFilesLocationTlFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("ArcFilesLocationTlFk1Link1");
  }

  /**
   * Container's getter for ArcFlsLocationsFk1Link1.
   * @return ArcFlsLocationsFk1Link1
   */
  public ViewLinkImpl getArcFlsLocationsFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("ArcFlsLocationsFk1Link1");
  }

  /**
   * Container's getter for ArcFlsLocationsTlFk1Link1.
   * @return ArcFlsLocationsTlFk1Link1
   */
  public ViewLinkImpl getArcFlsLocationsTlFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("ArcFlsLocationsTlFk1Link1");
  }

  /**
   * Container's getter for ArcFlsLocationsFkLink1.
   * @return ArcFlsLocationsFkLink1
   */
  public ViewLinkImpl getArcFlsLocationsFkLink1()
  {
    return (ViewLinkImpl) findViewLink("ArcFlsLocationsFkLink1");
  }

  /**
   * Container's getter for ArcFlStandardsTlFk1Link1.
   * @return ArcFlStandardsTlFk1Link1
   */
  public ViewLinkImpl getArcFlStandardsTlFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("ArcFlStandardsTlFk1Link1");
  }

  /**
   * Container's getter for HcmDepartmentsVwView2.
   * @return HcmDepartmentsVwView2
   */
  public ViewObjectImpl getHcmFileLocationDepartmentsView()
  {
    return (ViewObjectImpl) findViewObject("HcmFileLocationDepartmentsView");
  }

  /**
   * Container's getter for ArcFilesLocationView3.
   * @return ArcFilesLocationView3
   */
  public ViewObjectImpl getArcFilesLocationView3()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesLocationView3");
  }

  /**
   * Container's getter for HmcDepartmentsArcFileLocationLink1.
   * @return HmcDepartmentsArcFileLocationLink1
   */
  public ViewLinkImpl getHmcDepartmentsArcFileLocationLink1()
  {
    return (ViewLinkImpl) findViewLink("HmcDepartmentsArcFileLocationLink1");
  }

  /**
   * Container's getter for ArcFilesLocationTlView3.
   * @return ArcFilesLocationTlView3
   */
  public ViewObjectImpl getArcFilesLocationTlView3()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesLocationTlView3");
  }

  /**
   * Container's getter for ArcFilesLocationTlFk1Link2.
   * @return ArcFilesLocationTlFk1Link2
   */
  public ViewLinkImpl getArcFilesLocationTlFk1Link2()
  {
    return (ViewLinkImpl) findViewLink("ArcFilesLocationTlFk1Link2");
  }

  /**
   * Container's getter for ArcFlsLocationsTlView3.
   * @return ArcFlsLocationsTlView3
   */
  public ViewObjectImpl getArcFlsLocationsTlView3()
  {
    return (ViewObjectImpl) findViewObject("ArcFlsLocationsTlView3");
  }

  /**
   * Container's getter for ArcFlsLocationsTlFk1Link2.
   * @return ArcFlsLocationsTlFk1Link2
   */
  public ViewLinkImpl getArcFlsLocationsTlFk1Link2()
  {
    return (ViewLinkImpl) findViewLink("ArcFlsLocationsTlFk1Link2");
  }

  /**
   * Container's getter for ArcOldDocumentView2.
   * @return ArcOldDocumentView2
   */
  public ViewObjectImpl getArcDisposedOldDocumentView()
  {
    return (ViewObjectImpl) findViewObject("ArcDisposedOldDocumentView");
  }

  /**
   * Container's getter for ArcDocumentAttachmentView3.
   * @return ArcDocumentAttachmentView3
   */
  public ViewObjectImpl getArcDisposedDocumentAttachmentView()
  {
    return (ViewObjectImpl) findViewObject("ArcDisposedDocumentAttachmentView");
  }

  /**
   * Container's getter for ArcDocumentAttachmentFkLink2.
   * @return ArcDocumentAttachmentFkLink2
   */
  public ViewLinkImpl getArcDocumentAttachmentFkLink2()
  {
    return (ViewLinkImpl) findViewLink("ArcDocumentAttachmentFkLink2");
  }

  /**
   * Container's getter for ArcOldDocumentTlView3.
   * @return ArcOldDocumentTlView3
   */
  public ViewObjectImpl getArcDisposedOldDocumentTlView()
  {
    return (ViewObjectImpl) findViewObject("ArcDisposedOldDocumentTlView");
  }

  /**
   * Container's getter for ArcDocumentTlFkLink2.
   * @return ArcDocumentTlFkLink2
   */
  public ViewLinkImpl getArcDocumentTlFkLink2()
  {
    return (ViewLinkImpl) findViewLink("ArcDocumentTlFkLink2");
  }

  /**
   * Container's getter for ArcDocumentAttachmentTlView4.
   * @return ArcDocumentAttachmentTlView4
   */
  public ViewObjectImpl getArcDisposedDocumentAttachmentTlView()
  {
    return (ViewObjectImpl) findViewObject("ArcDisposedDocumentAttachmentTlView");
  }

  /**
   * Container's getter for ArcDocumentAttachmentTlFkLink3.
   * @return ArcDocumentAttachmentTlFkLink3
   */
  public ViewLinkImpl getArcDocumentAttachmentTlFkLink3()
  {
    return (ViewLinkImpl) findViewLink("ArcDocumentAttachmentTlFkLink3");
  }

  /**
   * Container's getter for ArcBorrowRequestsTlView1.
   * @return ArcBorrowRequestsTlView1
   */
  public ViewObjectImpl getArcBorrowRequestsTlView1()
  {
    return (ViewObjectImpl) findViewObject("ArcBorrowRequestsTlView1");
  }

  /**
   * Container's getter for ArcBorrowRequestsView1.
   * @return ArcBorrowRequestsView1
   */
  public ViewObjectImpl getArcBorrowRequestsView1()
  {
    return (ViewObjectImpl) findViewObject("ArcBorrowRequestsView1");
  }

  /**
   * Container's getter for ArcBorrowRequestsTlView2.
   * @return ArcBorrowRequestsTlView2
   */
  public ViewObjectImpl getArcBorrowRequestsTlView2()
  {
    return (ViewObjectImpl) findViewObject("ArcBorrowRequestsTlView2");
  }

  /**
   * Container's getter for ArcDocBorrowReqTlFk1Link1.
   * @return ArcDocBorrowReqTlFk1Link1
   */
  public ViewLinkImpl getArcDocBorrowReqTlFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("ArcDocBorrowReqTlFk1Link1");
  }

  /**
   * Container's getter for ArcFlsLocationsView4.
   * @return ArcFlsLocationsView4
   */
  public ViewObjectImpl getArcFlsLocationsView4()
  {
    return (ViewObjectImpl) findViewObject("ArcFlsLocationsView4");
  }

  /**
   * Container's getter for ArcFilesLocationMasterRVO1.
   * @return ArcFilesLocationMasterRVO1
   */
  public ArcFilesLocationMasterRVOImpl getArcFilesLocationMasterRVO()
  {
    return (ArcFilesLocationMasterRVOImpl) findViewObject("ArcFilesLocationMasterRVO");
}

  /**
   * Container's getter for BPMProcessTaskRVO1.
   * @return BPMProcessTaskRVO1
   */
  public ViewObjectImpl getBPMProcessTaskRVO1()
  {
    return (ViewObjectImpl) findViewObject("BPMProcessTaskRVO1");
  }

  /**
   * Container's getter for ArcFilesLocationDetailRVO1.
   * @return ArcFilesLocationDetailRVO1
   */
  public ArcFilesLocationDetailRVOImpl getArcFilesLocationDetailRVO()
  {
    return (ArcFilesLocationDetailRVOImpl) findViewObject("ArcFilesLocationDetailRVO");
  }

  /**
   * Container's getter for ArcFilesLocationMasterArcFilesLocationDetailLink1.
   * @return ArcFilesLocationMasterArcFilesLocationDetailLink1
   */
  public ViewLinkImpl getArcFilesLocationMasterArcFilesLocationDetailLink1()
  {
    return (ViewLinkImpl) findViewLink("ArcFilesLocationMasterArcFilesLocationDetailLink1");
  }

  /**
   * Container's getter for ArcFilesLocationDetailRVO1.
   * @return ArcFilesLocationDetailRVO1
   */
  public ArcFilesLocationDetailRVOImpl getArcFilesLocationDetailRVO1()
  {
    return (ArcFilesLocationDetailRVOImpl) findViewObject("ArcFilesLocationDetailRVO1");
  }

  /**
   * Container's getter for ArcFilesLocationDetailArcFilesLocationDetailLink1.
   * @return ArcFilesLocationDetailArcFilesLocationDetailLink1
   */
  public ViewLinkImpl getArcFilesLocationDetailArcFilesLocationDetailLink1()
  {
    return (ViewLinkImpl) findViewLink("ArcFilesLocationDetailArcFilesLocationDetailLink1");
  }

  /**
   * Container's getter for ArcFilesLocationView4.
   * @return ArcFilesLocationView4
   */
  public ViewObjectImpl getArcFilesLocationView4()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesLocationView4");
  }

  /**
   * Container's getter for ArcBorrowRequestsView2.
   * @return ArcBorrowRequestsView2
   */
  public ViewObjectImpl getArcBorrowRequestsView2()
  {
    return (ViewObjectImpl) findViewObject("ArcBorrowRequestsView2");
  }

  /**
   * Container's getter for ArcBorrowRequestsTlView3.
   * @return ArcBorrowRequestsTlView3
   */
  public ViewObjectImpl getArcBorrowRequestsTlView3()
  {
    return (ViewObjectImpl) findViewObject("ArcBorrowRequestsTlView3");
  }

  /**
   * Container's getter for ArcDocBorrowReqTlFk1Link2.
   * @return ArcDocBorrowReqTlFk1Link2
   */
  public ViewLinkImpl getArcDocBorrowReqTlFk1Link2()
  {
    return (ViewLinkImpl) findViewLink("ArcDocBorrowReqTlFk1Link2");
  }

  /**
   * Container's getter for BPMProcessTaskRVO2.
   * @return BPMProcessTaskRVO2
   */
  public ViewObjectImpl getBPMProcessTaskRVO2()
  {
    return (ViewObjectImpl) findViewObject("BPMProcessTaskRVO2");
  }

  /**
   * Container's getter for SsoUsersRVO1.
   * @return SsoUsersRVO1
   */
  public SsoUsersRVOImpl getSsoUsersRVO()
  {
    return (SsoUsersRVOImpl) findViewObject("SsoUsersRVO");
  }

  /**
   * Container's getter for ArcOldDocumentSsoUsersLink1.
   * @return ArcOldDocumentSsoUsersLink1
   */
  public ViewLinkImpl getArcOldDocumentSsoUsersLink1()
  {
    return (ViewLinkImpl) findViewLink("ArcOldDocumentSsoUsersLink1");
  }

  /**
   * Container's getter for SsoUsersRVO1.
   * @return SsoUsersRVO1
   */
  public SsoUsersRVOImpl getSsoUsersRVO1()
  {
    return (SsoUsersRVOImpl) findViewObject("SsoUsersRVO1");
  }

  /**
   * Container's getter for ArcOldDocumentSsoUsers2Link1.
   * @return ArcOldDocumentSsoUsers2Link1
   */
  public ViewLinkImpl getArcOldDocumentSsoUsers2Link1()
  {
    return (ViewLinkImpl) findViewLink("ArcOldDocumentSsoUsers2Link1");
  }

  /**
   * Container's getter for ArcFilesColumnsLockersTlView1.
   * @return ArcFilesColumnsLockersTlView1
   */
  public ViewObjectImpl getArcFilesColumnsLockersTlView1()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesColumnsLockersTlView1");
  }

  /**
   * Container's getter for ArcFilesColumnsLockersView1.
   * @return ArcFilesColumnsLockersView1
   */
  public ViewObjectImpl getArcFilesColumnsLockersView1()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesColumnsLockersView1");
  }

  /**
   * Container's getter for ArcFilesLockersTlView1.
   * @return ArcFilesLockersTlView1
   */
  public ViewObjectImpl getArcFilesLockersTlView1()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesLockersTlView1");
  }

  /**
   * Container's getter for ArcFilesLockersView1.
   * @return ArcFilesLockersView1
   */
  public ViewObjectImpl getArcFilesLockersView1()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesLockersView1");
  }

  /**
   * Container's getter for ArcFilesRowsColumnsLockersTlView1.
   * @return ArcFilesRowsColumnsLockersTlView1
   */
  public ViewObjectImpl getArcFilesRowsColumnsLockersTlView1()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesRowsColumnsLockersTlView1");
  }

  /**
   * Container's getter for ArcFilesRowsColumnsLockersView1.
   * @return ArcFilesRowsColumnsLockersView1
   */
  public ViewObjectImpl getArcFilesRowsColumnsLockersView1()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesRowsColumnsLockersView1");
  }

  /**
   * Container's getter for ArcFilesColumnsLockersTlView2.
   * @return ArcFilesColumnsLockersTlView2
   */
  public ViewObjectImpl getArcFilesColumnsLockersTlView2()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesColumnsLockersTlView2");
  }

  /**
   * Container's getter for ArcFilesColumnsLockersView2.
   * @return ArcFilesColumnsLockersView2
   */
  public ViewObjectImpl getArcFilesColumnsLockersView2()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesColumnsLockersView2");
  }

  /**
   * Container's getter for ArcFilesLockersTlView2.
   * @return ArcFilesLockersTlView2
   */
  public ViewObjectImpl getArcFilesLockersTlView2()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesLockersTlView2");
  }

  /**
   * Container's getter for ArcFilesRowsColumnsLockersView2.
   * @return ArcFilesRowsColumnsLockersView2
   */
  public ViewObjectImpl getArcFilesRowsColumnsLockersView2()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesRowsColumnsLockersView2");
  }

  /**
   * Container's getter for ArcFilesRowsColumnsLockersTlView2.
   * @return ArcFilesRowsColumnsLockersTlView2
   */
  public ViewObjectImpl getArcFilesRowsColumnsLockersTlView2()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesRowsColumnsLockersTlView2");
  }

  /**
   * Container's getter for ArcFilesColumnsLockersTlFk2Link1.
   * @return ArcFilesColumnsLockersTlFk2Link1
   */
  public ViewLinkImpl getArcFilesColumnsLockersTlFk2Link1()
  {
    return (ViewLinkImpl) findViewLink("ArcFilesColumnsLockersTlFk2Link1");
  }

  /**
   * Container's getter for ArcFilesColumnsLockersFk1Link1.
   * @return ArcFilesColumnsLockersFk1Link1
   */
  public ViewLinkImpl getArcFilesColumnsLockersFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("ArcFilesColumnsLockersFk1Link1");
  }

  /**
   * Container's getter for ArcFilesLockersTlFk2Link1.
   * @return ArcFilesLockersTlFk2Link1
   */
  public ViewLinkImpl getArcFilesLockersTlFk2Link1()
  {
    return (ViewLinkImpl) findViewLink("ArcFilesLockersTlFk2Link1");
  }

  /**
   * Container's getter for ArcFilesRowsColumnsLockersFk1Link1.
   * @return ArcFilesRowsColumnsLockersFk1Link1
   */
  public ViewLinkImpl getArcFilesRowsColumnsLockersFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("ArcFilesRowsColumnsLockersFk1Link1");
  }

  /**
   * Container's getter for ArcFilesRowsColumnsLockersTlFk2Link1.
   * @return ArcFilesRowsColumnsLockersTlFk2Link1
   */
  public ViewLinkImpl getArcFilesRowsColumnsLockersTlFk2Link1()
  {
    return (ViewLinkImpl) findViewLink("ArcFilesRowsColumnsLockersTlFk2Link1");
  }

  /**
   * Container's getter for ArcFilesLockersView2.
   * @return ArcFilesLockersView2
   */
  public ViewObjectImpl getArcFilesLockersView2()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesLockersView2");
  }

  /**
   * Container's getter for DepartmentLockersVl1.
   * @return DepartmentLockersVl1
   */
  public ViewLinkImpl getDepartmentLockersVl1()
  {
    return (ViewLinkImpl) findViewLink("DepartmentLockersVl1");
  }

  /**
   * Container's getter for ArcFilesLockersTlView3.
   * @return ArcFilesLockersTlView3
   */
  public ViewObjectImpl getArcFilesLockersTlView3()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesLockersTlView3");
  }

  /**
   * Container's getter for ArcFilesLockersTlFk2Link2.
   * @return ArcFilesLockersTlFk2Link2
   */
  public ViewLinkImpl getArcFilesLockersTlFk2Link2()
  {
    return (ViewLinkImpl) findViewLink("ArcFilesLockersTlFk2Link2");
  }

  /**
   * Container's getter for ArcFilesColumnsLockersView3.
   * @return ArcFilesColumnsLockersView3
   */
  public ViewObjectImpl getArcFilesColumnsLockersView3()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesColumnsLockersView3");
  }

  /**
   * Container's getter for ArcFilesColumnsLockersFk1Link2.
   * @return ArcFilesColumnsLockersFk1Link2
   */
  public ViewLinkImpl getArcFilesColumnsLockersFk1Link2()
  {
    return (ViewLinkImpl) findViewLink("ArcFilesColumnsLockersFk1Link2");
  }

  /**
   * Container's getter for ArcFilesColumnsLockersTlView3.
   * @return ArcFilesColumnsLockersTlView3
   */
  public ViewObjectImpl getArcFilesColumnsLockersTlView3()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesColumnsLockersTlView3");
  }

  /**
   * Container's getter for ArcFilesColumnsLockersTlFk2Link2.
   * @return ArcFilesColumnsLockersTlFk2Link2
   */
  public ViewLinkImpl getArcFilesColumnsLockersTlFk2Link2()
  {
    return (ViewLinkImpl) findViewLink("ArcFilesColumnsLockersTlFk2Link2");
  }

  /**
   * Container's getter for ArcFilesRowsColumnsLockersView3.
   * @return ArcFilesRowsColumnsLockersView3
   */
  public ViewObjectImpl getArcFilesRowsColumnsLockersView3()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesRowsColumnsLockersView3");
  }

  /**
   * Container's getter for ArcFilesRowsColumnsLockersFk1Link2.
   * @return ArcFilesRowsColumnsLockersFk1Link2
   */
  public ViewLinkImpl getArcFilesRowsColumnsLockersFk1Link2()
  {
    return (ViewLinkImpl) findViewLink("ArcFilesRowsColumnsLockersFk1Link2");
  }

  /**
   * Container's getter for ArcFilesRowsColumnsLockersTlView3.
   * @return ArcFilesRowsColumnsLockersTlView3
   */
  public ViewObjectImpl getArcFilesRowsColumnsLockersTlView3()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesRowsColumnsLockersTlView3");
  }

  /**
   * Container's getter for ArcFilesRowsColumnsLockersTlFk2Link2.
   * @return ArcFilesRowsColumnsLockersTlFk2Link2
   */
  public ViewLinkImpl getArcFilesRowsColumnsLockersTlFk2Link2()
  {
    return (ViewLinkImpl) findViewLink("ArcFilesRowsColumnsLockersTlFk2Link2");
  }

  /**
   * Container's getter for HcmDepartmentsVwView2.
   * @return HcmDepartmentsVwView2
   */
  public ViewObjectImpl getHcmDepartmentsVwDocumentView()
  {
    return (ViewObjectImpl) findViewObject("HcmDepartmentsVwDocumentView");
  }

  /**
   * Container's getter for ArcFilesLocationRVO1.
   * @return ArcFilesLocationRVO1
   */
  public ViewObjectImpl getArcFilesLocationRVO1()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesLocationRVO1");
  }

  /**
   * Container's getter for ArcFilesLocationDepartmentRVO1.
   * @return ArcFilesLocationDepartmentRVO1
   */
  public ArcFilesLocationDepartmentRVOImpl getArcFilesLocationDepartmentRVO()
  {
    return (ArcFilesLocationDepartmentRVOImpl) findViewObject("ArcFilesLocationDepartmentRVO");
  }

  /**
   * Container's getter for ArcFilesLocationDepartmentMasterRVO1.
   * @return ArcFilesLocationDepartmentMasterRVO1
   */
  public ArcFilesLocationDepartmentMasterRVOImpl getArcFilesLocationDepartmentMasterRVO()
  {
    return (ArcFilesLocationDepartmentMasterRVOImpl) findViewObject("ArcFilesLocationDepartmentMasterRVO");
  }

  /**
   * Container's getter for HcmDepartmentsVwViewArcFilesLocationMasterLink1.
   * @return HcmDepartmentsVwViewArcFilesLocationMasterLink1
   */
  public ViewLinkImpl getHcmDepartmentsVwViewArcFilesLocationMasterLink1()
  {
    return (ViewLinkImpl) findViewLink("HcmDepartmentsVwViewArcFilesLocationMasterLink1");
  }

  /**
   * Container's getter for ArcFileLocationDepartmentDetailRVO1.
   * @return ArcFileLocationDepartmentDetailRVO1
   */
  public ArcFileLocationDepartmentDetailRVOImpl getArcFileLocationDepartmentDetailRVO()
  {
    return (ArcFileLocationDepartmentDetailRVOImpl) findViewObject("ArcFileLocationDepartmentDetailRVO");
  }

  /**
   * Container's getter for ArcFilesLocationMasterFilesLocationDetailLink1.
   * @return ArcFilesLocationMasterFilesLocationDetailLink1
   */
  public ViewLinkImpl getArcFilesLocationMasterFilesLocationDetailLink1()
  {
    return (ViewLinkImpl) findViewLink("ArcFilesLocationMasterFilesLocationDetailLink1");
  }

  /**
   * Container's getter for ArcFileLocationDepartmentDetailRVO1.
   * @return ArcFileLocationDepartmentDetailRVO1
   */
  public ArcFileLocationDepartmentDetailRVOImpl getArcFileLocationDepartmentDetailRVO1()
  {
    return (ArcFileLocationDepartmentDetailRVOImpl) findViewObject("ArcFileLocationDepartmentDetailRVO1");
  }

  /**
   * Container's getter for ArcFilesLocationDepartmentDetailArcFilesLocationDetailLink1.
   * @return ArcFilesLocationDepartmentDetailArcFilesLocationDetailLink1
   */
  public ViewLinkImpl getArcFilesLocationDepartmentDetailArcFilesLocationDetailLink1()
  {
    return (ViewLinkImpl) findViewLink("ArcFilesLocationDepartmentDetailArcFilesLocationDetailLink1");
  }

  /**
   * Container's getter for ArcOldDocumentView2.
   * @return ArcOldDocumentView2
   */
  public ViewObjectImpl getArcOldDocumentView2()
  {
    return (ViewObjectImpl) findViewObject("ArcOldDocumentView2");
  }

  /**
   * Container's getter for ArcFileLocationArcOldDocumentLink1.
   * @return ArcFileLocationArcOldDocumentLink1
   */
  public ViewLinkImpl getArcFileLocationArcOldDocumentLink1()
  {
    return (ViewLinkImpl) findViewLink("ArcFileLocationArcOldDocumentLink1");
  }

  /**
   * Container's getter for ArcOldDocumentView4.
   * @return ArcOldDocumentView4
   */
  public ViewObjectImpl getArcOldDocumentView4()
  {
    return (ViewObjectImpl) findViewObject("ArcOldDocumentView4");
  }

  /**
   * Container's getter for ArcDocumentAttachmentView3.
   * @return ArcDocumentAttachmentView3
   */
  public ViewObjectImpl getArcDocumentAttachmentView3()
  {
    return (ViewObjectImpl) findViewObject("ArcDocumentAttachmentView3");
  }

  /**
   * Container's getter for ArcDocumentAttachmentFkLink3.
   * @return ArcDocumentAttachmentFkLink3
   */
  public ViewLinkImpl getArcDocumentAttachmentFkLink3()
  {
    return (ViewLinkImpl) findViewLink("ArcDocumentAttachmentFkLink3");
  }

  /**
   * Container's getter for ArcOldDocumentTlView3.
   * @return ArcOldDocumentTlView3
   */
  public ViewObjectImpl getArcOldDocumentTlView3()
  {
    return (ViewObjectImpl) findViewObject("ArcOldDocumentTlView3");
  }

  /**
   * Container's getter for ArcDocumentTlFkLink3.
   * @return ArcDocumentTlFkLink3
   */
  public ViewLinkImpl getArcDocumentTlFkLink3()
  {
    return (ViewLinkImpl) findViewLink("ArcDocumentTlFkLink3");
  }

  /**
   * Container's getter for ArcDocumentAttachmentTlView4.
   * @return ArcDocumentAttachmentTlView4
   */
  public ViewObjectImpl getArcDocumentAttachmentTlView4()
  {
    return (ViewObjectImpl) findViewObject("ArcDocumentAttachmentTlView4");
  }

  /**
   * Container's getter for ArcDocumentAttachmentTlFkLink4.
   * @return ArcDocumentAttachmentTlFkLink4
   */
  public ViewLinkImpl getArcDocumentAttachmentTlFkLink4()
  {
    return (ViewLinkImpl) findViewLink("ArcDocumentAttachmentTlFkLink4");
  }

  /**
   * Container's getter for ArcOldDocumentDashboardRVO1.
   * @return ArcOldDocumentDashboardRVO1
   */
  public ArcOldDocumentDashboardRVOImpl getArcOldDocumentDashboardRVO()
  {
    return (ArcOldDocumentDashboardRVOImpl) findViewObject("ArcOldDocumentDashboardRVO");
  }

  /**
   * Container's getter for ArcFileLocationWithNoDocumentRVO1.
   * @return ArcFileLocationWithNoDocumentRVO1
   */
  public ArcFileLocationWithNoDocumentRVOImpl getArcFileLocationWithNoDocumentRVO()
  {
    return (ArcFileLocationWithNoDocumentRVOImpl) findViewObject("ArcFileLocationWithNoDocumentRVO");
  }


  /**
   * Container's getter for BPMProcessTaskRVO3.
   * @return BPMProcessTaskRVO3
   */
  public ViewObjectImpl getBPMProcessTaskRVO3()
  {
    return (ViewObjectImpl) findViewObject("BPMProcessTaskRVO3");
  }

  /**
   * Container's getter for ArcOldDocumentView3.
   * @return ArcOldDocumentView3
   */
  public ViewObjectImpl getArcOldDocumentView3()
  {
    return (ViewObjectImpl) findViewObject("ArcOldDocumentView3");
  }

  /**
   * Container's getter for ArcDocumentAttachmentView4.
   * @return ArcDocumentAttachmentView4
   */
  public ViewObjectImpl getArcDocumentAttachmentView4()
  {
    return (ViewObjectImpl) findViewObject("ArcDocumentAttachmentView4");
  }

  /**
   * Container's getter for ArcDocumentAttachmentFkLink4.
   * @return ArcDocumentAttachmentFkLink4
   */
  public ViewLinkImpl getArcDocumentAttachmentFkLink4()
  {
    return (ViewLinkImpl) findViewLink("ArcDocumentAttachmentFkLink4");
  }

  /**
   * Container's getter for ArcOldDocumentTlView4.
   * @return ArcOldDocumentTlView4
   */
  public ViewObjectImpl getArcOldDocumentTlView4()
  {
    return (ViewObjectImpl) findViewObject("ArcOldDocumentTlView4");
  }

  /**
   * Container's getter for ArcDocumentTlFkLink4.
   * @return ArcDocumentTlFkLink4
   */
  public ViewLinkImpl getArcDocumentTlFkLink4()
  {
    return (ViewLinkImpl) findViewLink("ArcDocumentTlFkLink4");
  }

  /**
   * Container's getter for ArcDocumentAttachmentTlView5.
   * @return ArcDocumentAttachmentTlView5
   */
  public ViewObjectImpl getArcDocumentAttachmentTlView5()
  {
    return (ViewObjectImpl) findViewObject("ArcDocumentAttachmentTlView5");
  }

  /**
   * Container's getter for ArcDocumentAttachmentTlFkLink5.
   * @return ArcDocumentAttachmentTlFkLink5
   */
  public ViewLinkImpl getArcDocumentAttachmentTlFkLink5()
  {
    return (ViewLinkImpl) findViewLink("ArcDocumentAttachmentTlFkLink5");
  }

  /**
   * Container's getter for ArcFilesLocationPrivilegeView1.
   * @return ArcFilesLocationPrivilegeView1
   */
  public ViewObjectImpl getArcFilesLocationPrivilegeView1()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesLocationPrivilegeView1");
  }

  /**
   * Container's getter for FilesLocationsPrivVl1.
   * @return FilesLocationsPrivVl1
   */
  public ViewLinkImpl getFilesLocationsPrivVl1()
  {
    return (ViewLinkImpl) findViewLink("FilesLocationsPrivVl1");
  }

  /**
   * Container's getter for ArcFilesColumnsLockPrivView1.
   * @return ArcFilesColumnsLockPrivView1
   */
  public ViewObjectImpl getArcFilesColumnsLockPrivView1()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesColumnsLockPrivView1");
  }

  /**
   * Container's getter for FilesColumnsPrivVl1.
   * @return FilesColumnsPrivVl1
   */
  public ViewLinkImpl getFilesColumnsPrivVl1()
  {
    return (ViewLinkImpl) findViewLink("FilesColumnsPrivVl1");
  }

  /**
   * Container's getter for ArcFilesLockersPrivilegeView1.
   * @return ArcFilesLockersPrivilegeView1
   */
  public ViewObjectImpl getArcFilesLockersPrivilegeView1()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesLockersPrivilegeView1");
  }

  /**
   * Container's getter for FilesLockersPrivVl1.
   * @return FilesLockersPrivVl1
   */
  public ViewLinkImpl getFilesLockersPrivVl1()
  {
    return (ViewLinkImpl) findViewLink("FilesLockersPrivVl1");
  }

  /**
   * Container's getter for ArcFilesRCLockPrivView1.
   * @return ArcFilesRCLockPrivView1
   */
  public ViewObjectImpl getArcFilesRCLockPrivView1()
  {
    return (ViewObjectImpl) findViewObject("ArcFilesRCLockPrivView1");
  }

  /**
   * Container's getter for FilesRowsLockPrivVl1.
   * @return FilesRowsLockPrivVl1
   */
  public ViewLinkImpl getFilesRowsLockPrivVl1()
  {
    return (ViewLinkImpl) findViewLink("FilesRowsLockPrivVl1");
  }
}

