package arc.model.ro;

import java.math.BigDecimal;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;

import oracle.jbo.Key;
import oracle.jbo.RangePagingDataFilter;
import oracle.jbo.ScrollableDataFilter;
import oracle.jbo.server.ProgrammaticViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 17 15:47:04 AST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArcClassificationPVOImpl
  extends ProgrammaticViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public ArcClassificationPVOImpl()
  {
  }

  /**
   * getRangePagingData - for custom java data source support.
   */
  public Collection<Object> getRangePagingData(RangePagingDataFilter filter)
  {
    Collection<Object> value = super.getRangePagingData(filter);
    return value;
  }

  /**
   * retrieveDataByKey - for custom java data source support.
   */
  public Collection<Object> retrieveDataByKey(Key key, int size)
  {
    Collection<Object> value = super.retrieveDataByKey(key, size);
    return value;
  }

  /**
   * getScrollableData - for custom java data source support.
   */
  public Collection<Object> getScrollableData(ScrollableDataFilter filter)
  {
    ArrayList<Object> rows =  new ArrayList<Object>();
    HashMap<Object, Object> row = new HashMap<Object, Object>();
    row.put("StartPage", new BigDecimal(1));
    row.put("EndPage", new BigDecimal(10));
    row.put("Classification", "Test");
    rows.add(row);
    
    return rows;
  }

  @Override
  protected void executeQueryForCollection(Object object, Object[] object2, int i)
  {
    // TODO Implement this method
    super.executeQueryForCollection(object, object2, i);
  }
}

