package arc.model.ro;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 21 10:20:52 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArcFlStandardsRVOImpl
  extends ViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public ArcFlStandardsRVOImpl()
  {
  }
}

