package arc.model.ro;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 25 16:35:10 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArcFileLocationWithNoDocumentRVORowImpl
  extends ViewRowImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    FilesLocationPk,
    DisplayFilesLocationPk,
    DepartmentsFk,
    DisplayDepartmentsFk,
    DisplayFilesLocationPkSearch;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int FILESLOCATIONPK = AttributesEnum.FilesLocationPk.index();
  public static final int DISPLAYFILESLOCATIONPK = AttributesEnum.DisplayFilesLocationPk.index();
  public static final int DEPARTMENTSFK = AttributesEnum.DepartmentsFk.index();
  public static final int DISPLAYDEPARTMENTSFK = AttributesEnum.DisplayDepartmentsFk.index();
  public static final int DISPLAYFILESLOCATIONPKSEARCH = AttributesEnum.DisplayFilesLocationPkSearch.index();

  /**
   * This is the default constructor (do not remove).
   */
  public ArcFileLocationWithNoDocumentRVORowImpl()
  {
  }

  /**
   * Gets the attribute value for the calculated attribute FilesLocationPk.
   * @return the FilesLocationPk
   */
  public BigDecimal getFilesLocationPk()
  {
    return (BigDecimal) getAttributeInternal(FILESLOCATIONPK);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayFilesLocationPk.
   * @return the DisplayFilesLocationPk
   */
  public String getDisplayFilesLocationPk()
  {
    return (String) getAttributeInternal(DISPLAYFILESLOCATIONPK);
  }

  /**
   * Gets the attribute value for the calculated attribute DepartmentsFk.
   * @return the DepartmentsFk
   */
  public BigDecimal getDepartmentsFk()
  {
    return (BigDecimal) getAttributeInternal(DEPARTMENTSFK);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDepartmentsFk.
   * @return the DisplayDepartmentsFk
   */
  public String getDisplayDepartmentsFk()
  {
    return (String) getAttributeInternal(DISPLAYDEPARTMENTSFK);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayFilesLocationPkSearch.
   * @return the DisplayFilesLocationPkSearch
   */
  public String getDisplayFilesLocationPkSearch()
  {
    return (String) getAttributeInternal(DISPLAYFILESLOCATIONPK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayFilesLocationPkSearch.
   * @param value value to set the  DisplayFilesLocationPkSearch
   */
  public void setDisplayFilesLocationPkSearch(String value)
  {
    setAttributeInternal(DISPLAYFILESLOCATIONPKSEARCH, value);
  }
}

