package arc.model.ro;

import gen.common.GenLib;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 27 10:54:43 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArcOldDocumentRVOImpl
  extends ViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public ArcOldDocumentRVOImpl()
  {
  }

//
//  @Override
//  protected void executeQueryForCollection(Object object, Object[] object2, int i)
//  {
////    // TODO Implement this method
////    
////    String securityLevelWhereClause = GenLib.getFiterDocumentsBySecurityLevelsWhereClause("DOCUMENT_SECURITY_FK");
////    String fromDepartmentWhereClause = GenLib.getFilterByDepartmentWhereClause("FROM_DEPARTMENT_FK");
////    String toDepartmentWhereClause = GenLib.getFilterByDepartmentWhereClause("TO_DEPARTMENT_FK");
////    
////    String whereClause = securityLevelWhereClause + " AND " +
////            " ( (" + fromDepartmentWhereClause + ") OR (" + toDepartmentWhereClause + " ) )";
////    
////    System.out.println(securityLevelWhereClause);
////    System.out.println(fromDepartmentWhereClause);
////    System.out.println(toDepartmentWhereClause);
////    setWhereClause(whereClause);
////    System.err.println("whereClause : "+whereClause);
////    System.err.println("Query : "+getQuery()+"");
////    super.executeQueryForCollection(object, object2, i);
//  }
}

