package arc.model.ro;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 27 10:54:08 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArcOldDocumentRVORowImpl
  extends ViewRowImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    OldDocumentPk,
    DisplayOldDocumentPk,
    DocumentSecurityFk,
    FromDepartmentFk,
    ToDepartmentFk;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int OLDDOCUMENTPK = AttributesEnum.OldDocumentPk.index();
  public static final int DISPLAYOLDDOCUMENTPK = AttributesEnum.DisplayOldDocumentPk.index();
  public static final int DOCUMENTSECURITYFK = AttributesEnum.DocumentSecurityFk.index();
  public static final int FROMDEPARTMENTFK = AttributesEnum.FromDepartmentFk.index();
  public static final int TODEPARTMENTFK = AttributesEnum.ToDepartmentFk.index();

  /**
   * This is the default constructor (do not remove).
   */
  public ArcOldDocumentRVORowImpl()
  {
  }
}

