package arc.model.vo;

import arc.model.eo.ArcFlStandardsTlImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 09 14:51:06 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArcFlStandardsTlViewRowImpl
  extends ViewRowImpl
{
  public static final int ENTITY_ARCFLSTANDARDSTL = 0;

  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    FlStandardsTlPk,
    StandardDesc,
    LanguagesFk,
    FlStandardsFk,
    Notes,
    CreatedBy,
    CreationDate,
    ModifiedBy,
    ModifiedDate,
    UserDepartmentFk,
    NotesSearch,
    StandardDescSearch,
    SsoLanguagesVwView1;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }
  public static final int FLSTANDARDSTLPK = AttributesEnum.FlStandardsTlPk.index();
  public static final int STANDARDDESC = AttributesEnum.StandardDesc.index();
  public static final int LANGUAGESFK = AttributesEnum.LanguagesFk.index();
  public static final int FLSTANDARDSFK = AttributesEnum.FlStandardsFk.index();
  public static final int NOTES = AttributesEnum.Notes.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
  public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
  public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();
  public static final int NOTESSEARCH = AttributesEnum.NotesSearch.index();
  public static final int STANDARDDESCSEARCH = AttributesEnum.StandardDescSearch.index();
  public static final int SSOLANGUAGESVWVIEW1 = AttributesEnum.SsoLanguagesVwView1.index();

  /**
   * This is the default constructor (do not remove).
   */
  public ArcFlStandardsTlViewRowImpl()
  {
  }

  /**
   * Gets ArcFlStandardsTl entity object.
   * @return the ArcFlStandardsTl
   */
  public ArcFlStandardsTlImpl getArcFlStandardsTl()
  {
    return (ArcFlStandardsTlImpl) getEntity(ENTITY_ARCFLSTANDARDSTL);
  }

  /**
   * Gets the attribute value for FL_STANDARDS_TL_PK using the alias name FlStandardsTlPk.
   * @return the FL_STANDARDS_TL_PK
   */
  public BigDecimal getFlStandardsTlPk()
  {
    return (BigDecimal) getAttributeInternal(FLSTANDARDSTLPK);
  }

  /**
   * Sets <code>value</code> as attribute value for FL_STANDARDS_TL_PK using the alias name FlStandardsTlPk.
   * @param value value to set the FL_STANDARDS_TL_PK
   */
  public void setFlStandardsTlPk(BigDecimal value)
  {
    setAttributeInternal(FLSTANDARDSTLPK, value);
  }

  /**
   * Gets the attribute value for STANDARD_DESC using the alias name StandardDesc.
   * @return the STANDARD_DESC
   */
  public String getStandardDesc()
  {
    return (String) getAttributeInternal(STANDARDDESC);
  }

  /**
   * Sets <code>value</code> as attribute value for STANDARD_DESC using the alias name StandardDesc.
   * @param value value to set the STANDARD_DESC
   */
  public void setStandardDesc(String value)
  {
    setAttributeInternal(STANDARDDESC, value);
  }

  /**
   * Gets the attribute value for LANGUAGES_FK using the alias name LanguagesFk.
   * @return the LANGUAGES_FK
   */
  public BigDecimal getLanguagesFk()
  {
    return (BigDecimal) getAttributeInternal(LANGUAGESFK);
  }

  /**
   * Sets <code>value</code> as attribute value for LANGUAGES_FK using the alias name LanguagesFk.
   * @param value value to set the LANGUAGES_FK
   */
  public void setLanguagesFk(BigDecimal value)
  {
    setAttributeInternal(LANGUAGESFK, value);
  }

  /**
   * Gets the attribute value for FL_STANDARDS_FK using the alias name FlStandardsFk.
   * @return the FL_STANDARDS_FK
   */
  public BigDecimal getFlStandardsFk()
  {
    return (BigDecimal) getAttributeInternal(FLSTANDARDSFK);
  }

  /**
   * Sets <code>value</code> as attribute value for FL_STANDARDS_FK using the alias name FlStandardsFk.
   * @param value value to set the FL_STANDARDS_FK
   */
  public void setFlStandardsFk(BigDecimal value)
  {
    setAttributeInternal(FLSTANDARDSFK, value);
  }

  /**
   * Gets the attribute value for NOTES using the alias name Notes.
   * @return the NOTES
   */
  public String getNotes()
  {
    return (String) getAttributeInternal(NOTES);
  }

  /**
   * Sets <code>value</code> as attribute value for NOTES using the alias name Notes.
   * @param value value to set the NOTES
   */
  public void setNotes(String value)
  {
    setAttributeInternal(NOTES, value);
  }

  /**
   * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
   * @return the CREATED_BY
   */
  public BigDecimal getCreatedBy()
  {
    return (BigDecimal) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
   * @param value value to set the CREATED_BY
   */
  public void setCreatedBy(BigDecimal value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
   * @return the CREATION_DATE
   */
  public Timestamp getCreationDate()
  {
    return (Timestamp) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
   * @param value value to set the CREATION_DATE
   */
  public void setCreationDate(Timestamp value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
   * @return the MODIFIED_BY
   */
  public BigDecimal getModifiedBy()
  {
    return (BigDecimal) getAttributeInternal(MODIFIEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
   * @param value value to set the MODIFIED_BY
   */
  public void setModifiedBy(BigDecimal value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
   * @return the MODIFIED_DATE
   */
  public Timestamp getModifiedDate()
  {
    return (Timestamp) getAttributeInternal(MODIFIEDDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
   * @param value value to set the MODIFIED_DATE
   */
  public void setModifiedDate(Timestamp value)
  {
    setAttributeInternal(MODIFIEDDATE, value);
  }

  /**
   * Gets the attribute value for USER_DEPARTMENT_FK using the alias name UserDepartmentFk.
   * @return the USER_DEPARTMENT_FK
   */
  public BigDecimal getUserDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as attribute value for USER_DEPARTMENT_FK using the alias name UserDepartmentFk.
   * @param value value to set the USER_DEPARTMENT_FK
   */
  public void setUserDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(USERDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute NotesSearch.
   * @return the NotesSearch
   */
  public String getNotesSearch()
  {
    return (String) getAttributeInternal(NOTES);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute NotesSearch.
   * @param value value to set the  NotesSearch
   */
  public void setNotesSearch(String value)
  {
    setAttributeInternal(NOTESSEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute StandardDescSearch.
   * @return the StandardDescSearch
   */
  public String getStandardDescSearch()
  {
    return (String) getAttributeInternal(STANDARDDESC);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute StandardDescSearch.
   * @param value value to set the  StandardDescSearch
   */
  public void setStandardDescSearch(String value)
  {
    setAttributeInternal(STANDARDDESCSEARCH, value);
  }

  /**
   * Gets the view accessor <code>RowSet</code> SsoLanguagesVwView1.
   */
  public RowSet getSsoLanguagesVwView1()
  {
    return (RowSet) getAttributeInternal(SSOLANGUAGESVWVIEW1);
  }
}

