package arc.model.vo;

import arc.model.eo.ArcFlStandardsImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 09 15:13:09 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArcFlStandardsViewRowImpl
  extends ViewRowImpl
{

  public static final int ENTITY_ARCFLSTANDARDS = 0;

  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    FlStandardsPk,
    FlStatusFl,
    CreatedBy,
    CreationDate,
    ModifiedBy,
    ModifiedDate,
    UserDepartmentFk,
    DisplayStandardDesc,
    DisplayNotes,
    DisplayStandardDescSearch,
    DisplayNotesSearch,
    ArcFlsLocationsView,
    ArcFlStandardsTlView;
    private static AttributesEnum[] vals = null;
    ;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }

  public static final int FLSTANDARDSPK = AttributesEnum.FlStandardsPk.index();
  public static final int FLSTATUSFL = AttributesEnum.FlStatusFl.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
  public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
  public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();
  public static final int DISPLAYSTANDARDDESC = AttributesEnum.DisplayStandardDesc.index();
  public static final int DISPLAYNOTES = AttributesEnum.DisplayNotes.index();
  public static final int DISPLAYSTANDARDDESCSEARCH = AttributesEnum.DisplayStandardDescSearch.index();
  public static final int DISPLAYNOTESSEARCH = AttributesEnum.DisplayNotesSearch.index();
  public static final int ARCFLSLOCATIONSVIEW = AttributesEnum.ArcFlsLocationsView.index();
  public static final int ARCFLSTANDARDSTLVIEW = AttributesEnum.ArcFlStandardsTlView.index();

  /**
   * This is the default constructor (do not remove).
   */
  public ArcFlStandardsViewRowImpl()
  {
  }

  /**
   * Gets ArcFlStandards entity object.
   * @return the ArcFlStandards
   */
  public ArcFlStandardsImpl getArcFlStandards()
  {
    return (ArcFlStandardsImpl) getEntity(ENTITY_ARCFLSTANDARDS);
  }

  /**
   * Gets the attribute value for FL_STANDARDS_PK using the alias name FlStandardsPk.
   * @return the FL_STANDARDS_PK
   */
  public BigDecimal getFlStandardsPk()
  {
    return (BigDecimal) getAttributeInternal(FLSTANDARDSPK);
  }

  /**
   * Sets <code>value</code> as attribute value for FL_STANDARDS_PK using the alias name FlStandardsPk.
   * @param value value to set the FL_STANDARDS_PK
   */
  public void setFlStandardsPk(BigDecimal value)
  {
    setAttributeInternal(FLSTANDARDSPK, value);
  }

  /**
   * Gets the attribute value for FL_STATUS_FL using the alias name FlStatusFl.
   * @return the FL_STATUS_FL
   */
  public BigDecimal getFlStatusFl()
  {
    return (BigDecimal) getAttributeInternal(FLSTATUSFL);
  }

  /**
   * Sets <code>value</code> as attribute value for FL_STATUS_FL using the alias name FlStatusFl.
   * @param value value to set the FL_STATUS_FL
   */
  public void setFlStatusFl(BigDecimal value)
  {
    setAttributeInternal(FLSTATUSFL, value);
  }

  /**
   * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
   * @return the CREATED_BY
   */
  public BigDecimal getCreatedBy()
  {
    return (BigDecimal) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
   * @param value value to set the CREATED_BY
   */
  public void setCreatedBy(BigDecimal value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
   * @return the CREATION_DATE
   */
  public Timestamp getCreationDate()
  {
    return (Timestamp) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
   * @param value value to set the CREATION_DATE
   */
  public void setCreationDate(Timestamp value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
   * @return the MODIFIED_BY
   */
  public BigDecimal getModifiedBy()
  {
    return (BigDecimal) getAttributeInternal(MODIFIEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
   * @param value value to set the MODIFIED_BY
   */
  public void setModifiedBy(BigDecimal value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
   * @return the MODIFIED_DATE
   */
  public Timestamp getModifiedDate()
  {
    return (Timestamp) getAttributeInternal(MODIFIEDDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
   * @param value value to set the MODIFIED_DATE
   */
  public void setModifiedDate(Timestamp value)
  {
    setAttributeInternal(MODIFIEDDATE, value);
  }

  /**
   * Gets the attribute value for USER_DEPARTMENT_FK using the alias name UserDepartmentFk.
   * @return the USER_DEPARTMENT_FK
   */
  public BigDecimal getUserDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as attribute value for USER_DEPARTMENT_FK using the alias name UserDepartmentFk.
   * @param value value to set the USER_DEPARTMENT_FK
   */
  public void setUserDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(USERDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for DISPLAY_STANDARD_DESC using the alias name DisplayStandardDesc.
   * @return the DISPLAY_STANDARD_DESC
   */
  public String getDisplayStandardDesc()
  {
    return (String) getAttributeInternal(DISPLAYSTANDARDDESC);
  }

  /**
   * Sets <code>value</code> as attribute value for DISPLAY_STANDARD_DESC using the alias name DisplayStandardDesc.
   * @param value value to set the DISPLAY_STANDARD_DESC
   */
  public void setDisplayStandardDesc(String value)
  {
    setAttributeInternal(DISPLAYSTANDARDDESC, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayStandardDescSearch.
   * @return the DisplayStandardDescSearch
   */
  public String getDisplayStandardDescSearch()
  {
    return (String) getAttributeInternal(DISPLAYSTANDARDDESC);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayStandardDescSearch.
   * @param value value to set the  DisplayStandardDescSearch
   */
  public void setDisplayStandardDescSearch(String value)
  {
    setAttributeInternal(DISPLAYSTANDARDDESCSEARCH, value);
  }

  /**
   * Gets the attribute value for DISPLAY_NOTES using the alias name DisplayNotes.
   * @return the DISPLAY_NOTES
   */
  public String getDisplayNotes()
  {
    return (String) getAttributeInternal(DISPLAYNOTES);
  }

  /**
   * Sets <code>value</code> as attribute value for DISPLAY_NOTES using the alias name DisplayNotes.
   * @param value value to set the DISPLAY_NOTES
   */
  public void setDisplayNotes(String value)
  {
    setAttributeInternal(DISPLAYNOTES, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayNotesSearch.
   * @return the DisplayNotesSearch
   */
  public String getDisplayNotesSearch()
  {
    return (String) getAttributeInternal(DISPLAYNOTES);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayNotesSearch.
   * @param value value to set the  DisplayNotesSearch
   */
  public void setDisplayNotesSearch(String value)
  {
    setAttributeInternal(DISPLAYNOTESSEARCH, value);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link ArcFlsLocationsView.
   */
  public RowIterator getArcFlsLocationsView()
  {
    return (RowIterator) getAttributeInternal(ARCFLSLOCATIONSVIEW);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link ArcFlStandardsTlView.
   */
  public RowIterator getArcFlStandardsTlView()
  {
    return (RowIterator) getAttributeInternal(ARCFLSTANDARDSTLVIEW);
  }
}

