package arc.model.vo;

import arc.model.eo.ArcFilesLockersImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 11 10:32:01 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArcFilesLockersViewRowImpl
  extends ViewRowImpl
{


  public static final int ENTITY_ARCFILESLOCKERS = 0;

  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    FilesLockersPk,
    DepartmentsFk,
    CreatedBy,
    CreationDate,
    ModifiedBy,
    ModifiedDate,
    UserDepartmentFk,
    DisplayFilesLockersName,
    DisplayFilesLockersNameSearch,
    DisplayFilesLockersDesc,
    DisplayFilesLockersDescSearch,
    DisplayFilesLockersLocation,
    DisplayFilesLockersLocationSearch,
    ArcFilesColumnsLockersView,
    ArcFilesLockersTlView,
    ArcFilesLockersPrivilegeView;
    private static AttributesEnum[] vals = null;
    ;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int FILESLOCKERSPK = AttributesEnum.FilesLockersPk.index();
  public static final int DEPARTMENTSFK = AttributesEnum.DepartmentsFk.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
  public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
  public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();
  public static final int DISPLAYFILESLOCKERSNAME = AttributesEnum.DisplayFilesLockersName.index();
  public static final int DISPLAYFILESLOCKERSNAMESEARCH = AttributesEnum.DisplayFilesLockersNameSearch.index();
  public static final int DISPLAYFILESLOCKERSDESC = AttributesEnum.DisplayFilesLockersDesc.index();
  public static final int DISPLAYFILESLOCKERSDESCSEARCH = AttributesEnum.DisplayFilesLockersDescSearch.index();
  public static final int DISPLAYFILESLOCKERSLOCATION = AttributesEnum.DisplayFilesLockersLocation.index();
  public static final int DISPLAYFILESLOCKERSLOCATIONSEARCH = AttributesEnum.DisplayFilesLockersLocationSearch.index();
  public static final int ARCFILESCOLUMNSLOCKERSVIEW = AttributesEnum.ArcFilesColumnsLockersView.index();
  public static final int ARCFILESLOCKERSTLVIEW = AttributesEnum.ArcFilesLockersTlView.index();
  public static final int ARCFILESLOCKERSPRIVILEGEVIEW = AttributesEnum.ArcFilesLockersPrivilegeView.index();

  /**
   * This is the default constructor (do not remove).
   */
  public ArcFilesLockersViewRowImpl()
  {
  }

  /**
   * Gets ArcFilesLockers entity object.
   * @return the ArcFilesLockers
   */
  public ArcFilesLockersImpl getArcFilesLockers()
  {
    return (ArcFilesLockersImpl) getEntity(ENTITY_ARCFILESLOCKERS);
  }

  /**
   * Gets the attribute value for FILES_LOCKERS_PK using the alias name FilesLockersPk.
   * @return the FILES_LOCKERS_PK
   */
  public BigDecimal getFilesLockersPk()
  {
    return (BigDecimal) getAttributeInternal(FILESLOCKERSPK);
  }

  /**
   * Sets <code>value</code> as attribute value for FILES_LOCKERS_PK using the alias name FilesLockersPk.
   * @param value value to set the FILES_LOCKERS_PK
   */
  public void setFilesLockersPk(BigDecimal value)
  {
    setAttributeInternal(FILESLOCKERSPK, value);
  }

  /**
   * Gets the attribute value for DEPARTMENTS_FK using the alias name DepartmentsFk.
   * @return the DEPARTMENTS_FK
   */
  public BigDecimal getDepartmentsFk()
  {
    return (BigDecimal) getAttributeInternal(DEPARTMENTSFK);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPARTMENTS_FK using the alias name DepartmentsFk.
   * @param value value to set the DEPARTMENTS_FK
   */
  public void setDepartmentsFk(BigDecimal value)
  {
    setAttributeInternal(DEPARTMENTSFK, value);
  }

  /**
   * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
   * @return the CREATED_BY
   */
  public BigDecimal getCreatedBy()
  {
    return (BigDecimal) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
   * @param value value to set the CREATED_BY
   */
  public void setCreatedBy(BigDecimal value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
   * @return the CREATION_DATE
   */
  public Timestamp getCreationDate()
  {
    return (Timestamp) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
   * @param value value to set the CREATION_DATE
   */
  public void setCreationDate(Timestamp value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
   * @return the MODIFIED_BY
   */
  public BigDecimal getModifiedBy()
  {
    return (BigDecimal) getAttributeInternal(MODIFIEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
   * @param value value to set the MODIFIED_BY
   */
  public void setModifiedBy(BigDecimal value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
   * @return the MODIFIED_DATE
   */
  public Timestamp getModifiedDate()
  {
    return (Timestamp) getAttributeInternal(MODIFIEDDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
   * @param value value to set the MODIFIED_DATE
   */
  public void setModifiedDate(Timestamp value)
  {
    setAttributeInternal(MODIFIEDDATE, value);
  }

  /**
   * Gets the attribute value for USER_DEPARTMENT_FK using the alias name UserDepartmentFk.
   * @return the USER_DEPARTMENT_FK
   */
  public BigDecimal getUserDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as attribute value for USER_DEPARTMENT_FK using the alias name UserDepartmentFk.
   * @param value value to set the USER_DEPARTMENT_FK
   */
  public void setUserDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(USERDEPARTMENTFK, value);
  }


  /**
   * Gets the attribute value for DISPLAY_FILES_LOCKERS_NAME using the alias name DisplayFilesLockersName.
   * @return the DISPLAY_FILES_LOCKERS_NAME
   */
  public String getDisplayFilesLockersName()
  {
    return (String) getAttributeInternal(DISPLAYFILESLOCKERSNAME);
  }

  /**
   * Sets <code>value</code> as attribute value for DISPLAY_FILES_LOCKERS_NAME using the alias name DisplayFilesLockersName.
   * @param value value to set the DISPLAY_FILES_LOCKERS_NAME
   */
  public void setDisplayFilesLockersName(String value)
  {
    setAttributeInternal(DISPLAYFILESLOCKERSNAME, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayFilesLockersNameSearch.
   * @return the DisplayFilesLockersNameSearch
   */
  public String getDisplayFilesLockersNameSearch()
  {
    return (String) getAttributeInternal(DISPLAYFILESLOCKERSNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayFilesLockersNameSearch.
   * @param value value to set the  DisplayFilesLockersNameSearch
   */
  public void setDisplayFilesLockersNameSearch(String value)
  {
    setAttributeInternal(DISPLAYFILESLOCKERSNAMESEARCH, value);
  }

  /**
   * Gets the attribute value for DISPLAY_FILES_LOCKERS_DESC using the alias name DisplayFilesLockersDesc.
   * @return the DISPLAY_FILES_LOCKERS_DESC
   */
  public String getDisplayFilesLockersDesc()
  {
    return (String) getAttributeInternal(DISPLAYFILESLOCKERSDESC);
  }

  /**
   * Sets <code>value</code> as attribute value for DISPLAY_FILES_LOCKERS_DESC using the alias name DisplayFilesLockersDesc.
   * @param value value to set the DISPLAY_FILES_LOCKERS_DESC
   */
  public void setDisplayFilesLockersDesc(String value)
  {
    setAttributeInternal(DISPLAYFILESLOCKERSDESC, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayFilesLockersDescSearch.
   * @return the DisplayFilesLockersDescSearch
   */
  public String getDisplayFilesLockersDescSearch()
  {
    return (String) getAttributeInternal(DISPLAYFILESLOCKERSDESC);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayFilesLockersDescSearch.
   * @param value value to set the  DisplayFilesLockersDescSearch
   */
  public void setDisplayFilesLockersDescSearch(String value)
  {
    setAttributeInternal(DISPLAYFILESLOCKERSDESCSEARCH, value);
  }

  /**
   * Gets the attribute value for DISPLAY_FILES_LOCKERS_LOCATION using the alias name DisplayFilesLockersLocation.
   * @return the DISPLAY_FILES_LOCKERS_LOCATION
   */
  public String getDisplayFilesLockersLocation()
  {
    return (String) getAttributeInternal(DISPLAYFILESLOCKERSLOCATION);
  }

  /**
   * Sets <code>value</code> as attribute value for DISPLAY_FILES_LOCKERS_LOCATION using the alias name DisplayFilesLockersLocation.
   * @param value value to set the DISPLAY_FILES_LOCKERS_LOCATION
   */
  public void setDisplayFilesLockersLocation(String value)
  {
    setAttributeInternal(DISPLAYFILESLOCKERSLOCATION, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayFilesLockersLocationSearch.
   * @return the DisplayFilesLockersLocationSearch
   */
  public String getDisplayFilesLockersLocationSearch()
  {
    return (String) getAttributeInternal(DISPLAYFILESLOCKERSLOCATION);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayFilesLockersLocationSearch.
   * @param value value to set the  DisplayFilesLockersLocationSearch
   */
  public void setDisplayFilesLockersLocationSearch(String value)
  {
    setAttributeInternal(DISPLAYFILESLOCKERSLOCATIONSEARCH, value);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link ArcFilesColumnsLockersView.
   */
  public RowIterator getArcFilesColumnsLockersView()
  {
    return (RowIterator) getAttributeInternal(ARCFILESCOLUMNSLOCKERSVIEW);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link ArcFilesLockersTlView.
   */
  public RowIterator getArcFilesLockersTlView()
  {
    return (RowIterator) getAttributeInternal(ARCFILESLOCKERSTLVIEW);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link ArcFilesLockersPrivilegeView.
   */
  public RowIterator getArcFilesLockersPrivilegeView()
  {
    return (RowIterator) getAttributeInternal(ARCFILESLOCKERSPRIVILEGEVIEW);
  }
}

