package arc.model.vo;

import arc.model.eo.ArcFlsLocationsImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 09 16:11:49 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArcFlsLocationsViewRowImpl
  extends ViewRowImpl
{


  public static final int ENTITY_ARCFLSLOCATIONS = 0;

  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    FlsLocationsPk,
    MainLocationFk,
    FlStandardsFk,
    CreatedBy,
    CreationDate,
    ModifiedBy,
    ModifiedDate,
    UserDepartmentFk,
    DisplayMainLocationFk,
    DisplayFileLocationDesc,
    DisplayNotes,
    DisplayMainLocationFkSearch,
    DisplayFileLocationDescSearch,
    DisplayNotesSearch,
    MainLocationFkSearch,
    ArcFlsLocationsView,
    ArcFlsLocationsTlView,
    ArcFlsLocationsMainLocationFk,
    ArcFlsLocationsRVO;
    private static AttributesEnum[] vals = null;
    ;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int FLSLOCATIONSPK = AttributesEnum.FlsLocationsPk.index();
  public static final int MAINLOCATIONFK = AttributesEnum.MainLocationFk.index();
  public static final int FLSTANDARDSFK = AttributesEnum.FlStandardsFk.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
  public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
  public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();
  public static final int DISPLAYMAINLOCATIONFK = AttributesEnum.DisplayMainLocationFk.index();
  public static final int DISPLAYFILELOCATIONDESC = AttributesEnum.DisplayFileLocationDesc.index();
  public static final int DISPLAYNOTES = AttributesEnum.DisplayNotes.index();
  public static final int DISPLAYMAINLOCATIONFKSEARCH = AttributesEnum.DisplayMainLocationFkSearch.index();
  public static final int DISPLAYFILELOCATIONDESCSEARCH = AttributesEnum.DisplayFileLocationDescSearch.index();
  public static final int DISPLAYNOTESSEARCH = AttributesEnum.DisplayNotesSearch.index();
  public static final int MAINLOCATIONFKSEARCH = AttributesEnum.MainLocationFkSearch.index();
  public static final int ARCFLSLOCATIONSVIEW = AttributesEnum.ArcFlsLocationsView.index();
  public static final int ARCFLSLOCATIONSTLVIEW = AttributesEnum.ArcFlsLocationsTlView.index();
  public static final int ARCFLSLOCATIONSMAINLOCATIONFK = AttributesEnum.ArcFlsLocationsMainLocationFk.index();
  public static final int ARCFLSLOCATIONSRVO = AttributesEnum.ArcFlsLocationsRVO.index();

  /**
   * This is the default constructor (do not remove).
   */
  public ArcFlsLocationsViewRowImpl()
  {
  }

  /**
   * Gets ArcFlsLocations entity object.
   * @return the ArcFlsLocations
   */
  public ArcFlsLocationsImpl getArcFlsLocations()
  {
    return (ArcFlsLocationsImpl) getEntity(ENTITY_ARCFLSLOCATIONS);
  }

  /**
   * Gets the attribute value for FLS_LOCATIONS_PK using the alias name FlsLocationsPk.
   * @return the FLS_LOCATIONS_PK
   */
  public BigDecimal getFlsLocationsPk()
  {
    return (BigDecimal) getAttributeInternal(FLSLOCATIONSPK);
  }

  /**
   * Sets <code>value</code> as attribute value for FLS_LOCATIONS_PK using the alias name FlsLocationsPk.
   * @param value value to set the FLS_LOCATIONS_PK
   */
  public void setFlsLocationsPk(BigDecimal value)
  {
    setAttributeInternal(FLSLOCATIONSPK, value);
  }

  /**
   * Gets the attribute value for MAIN_LOCATION_FK using the alias name MainLocationFk.
   * @return the MAIN_LOCATION_FK
   */
  public BigDecimal getMainLocationFk()
  {
    return (BigDecimal) getAttributeInternal(MAINLOCATIONFK);
  }

  /**
   * Sets <code>value</code> as attribute value for MAIN_LOCATION_FK using the alias name MainLocationFk.
   * @param value value to set the MAIN_LOCATION_FK
   */
  public void setMainLocationFk(BigDecimal value)
  {
    setAttributeInternal(MAINLOCATIONFK, value);
  }

  /**
   * Gets the attribute value for FL_STANDARDS_FK using the alias name FlStandardsFk.
   * @return the FL_STANDARDS_FK
   */
  public BigDecimal getFlStandardsFk()
  {
    return (BigDecimal) getAttributeInternal(FLSTANDARDSFK);
  }

  /**
   * Sets <code>value</code> as attribute value for FL_STANDARDS_FK using the alias name FlStandardsFk.
   * @param value value to set the FL_STANDARDS_FK
   */
  public void setFlStandardsFk(BigDecimal value)
  {
    setAttributeInternal(FLSTANDARDSFK, value);
  }

  /**
   * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
   * @return the CREATED_BY
   */
  public BigDecimal getCreatedBy()
  {
    return (BigDecimal) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
   * @param value value to set the CREATED_BY
   */
  public void setCreatedBy(BigDecimal value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
   * @return the CREATION_DATE
   */
  public Timestamp getCreationDate()
  {
    return (Timestamp) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
   * @param value value to set the CREATION_DATE
   */
  public void setCreationDate(Timestamp value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
   * @return the MODIFIED_BY
   */
  public BigDecimal getModifiedBy()
  {
    return (BigDecimal) getAttributeInternal(MODIFIEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
   * @param value value to set the MODIFIED_BY
   */
  public void setModifiedBy(BigDecimal value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
   * @return the MODIFIED_DATE
   */
  public Timestamp getModifiedDate()
  {
    return (Timestamp) getAttributeInternal(MODIFIEDDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
   * @param value value to set the MODIFIED_DATE
   */
  public void setModifiedDate(Timestamp value)
  {
    setAttributeInternal(MODIFIEDDATE, value);
  }

  /**
   * Gets the attribute value for USER_DEPARTMENT_FK using the alias name UserDepartmentFk.
   * @return the USER_DEPARTMENT_FK
   */
  public BigDecimal getUserDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as attribute value for USER_DEPARTMENT_FK using the alias name UserDepartmentFk.
   * @param value value to set the USER_DEPARTMENT_FK
   */
  public void setUserDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(USERDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayMainLocationFk.
   * @return the DisplayMainLocationFk
   */
  public String getDisplayMainLocationFk()
  {
    return (String) getAttributeInternal(DISPLAYMAINLOCATIONFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayMainLocationFk.
   * @param value value to set the  DisplayMainLocationFk
   */
  public void setDisplayMainLocationFk(String value)
  {
    setAttributeInternal(DISPLAYMAINLOCATIONFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayMainLocationFkSearch.
   * @return the DisplayMainLocationFkSearch
   */
  public String getDisplayMainLocationFkSearch()
  {
    return (String) getAttributeInternal(DISPLAYMAINLOCATIONFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayMainLocationFkSearch.
   * @param value value to set the  DisplayMainLocationFkSearch
   */
  public void setDisplayMainLocationFkSearch(String value)
  {
    setAttributeInternal(DISPLAYMAINLOCATIONFKSEARCH, value);
  }

  /**
   * Gets the attribute value for DISPLAY_FILE_LOCATION_DESC using the alias name DisplayFileLocationDesc.
   * @return the DISPLAY_FILE_LOCATION_DESC
   */
  public String getDisplayFileLocationDesc()
  {
    return (String) getAttributeInternal(DISPLAYFILELOCATIONDESC);
  }

  /**
   * Sets <code>value</code> as attribute value for DISPLAY_FILE_LOCATION_DESC using the alias name DisplayFileLocationDesc.
   * @param value value to set the DISPLAY_FILE_LOCATION_DESC
   */
  public void setDisplayFileLocationDesc(String value)
  {
    setAttributeInternal(DISPLAYFILELOCATIONDESC, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayFileLocationDescSearch.
   * @return the DisplayFileLocationDescSearch
   */
  public String getDisplayFileLocationDescSearch()
  {
    return (String) getAttributeInternal(DISPLAYFILELOCATIONDESC);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayFileLocationDescSearch.
   * @param value value to set the  DisplayFileLocationDescSearch
   */
  public void setDisplayFileLocationDescSearch(String value)
  {
    setAttributeInternal(DISPLAYFILELOCATIONDESCSEARCH, value);
  }

  /**
   * Gets the attribute value for DISPLAY_NOTES using the alias name DisplayNotes.
   * @return the DISPLAY_NOTES
   */
  public String getDisplayNotes()
  {
    return (String) getAttributeInternal(DISPLAYNOTES);
  }

  /**
   * Sets <code>value</code> as attribute value for DISPLAY_NOTES using the alias name DisplayNotes.
   * @param value value to set the DISPLAY_NOTES
   */
  public void setDisplayNotes(String value)
  {
    setAttributeInternal(DISPLAYNOTES, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayNotesSearch.
   * @return the DisplayNotesSearch
   */
  public String getDisplayNotesSearch()
  {
    return (String) getAttributeInternal(DISPLAYNOTES);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayNotesSearch.
   * @param value value to set the  DisplayNotesSearch
   */
  public void setDisplayNotesSearch(String value)
  {
    setAttributeInternal(DISPLAYNOTESSEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute MainLocationFkSearch.
   * @return the MainLocationFkSearch
   */
  public BigDecimal getMainLocationFkSearch()
  {
    return (BigDecimal) getAttributeInternal(MAINLOCATIONFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute MainLocationFkSearch.
   * @param value value to set the  MainLocationFkSearch
   */
  public void setMainLocationFkSearch(BigDecimal value)
  {
    setAttributeInternal(MAINLOCATIONFKSEARCH, value);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link ArcFlsLocationsView.
   */
  public RowIterator getArcFlsLocationsView()
  {
    return (RowIterator) getAttributeInternal(ARCFLSLOCATIONSVIEW);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link ArcFlsLocationsTlView.
   */
  public RowIterator getArcFlsLocationsTlView()
  {
    return (RowIterator) getAttributeInternal(ARCFLSLOCATIONSTLVIEW);
  }

  /**
   * Gets the view accessor <code>RowSet</code> ArcFlsLocationsMainLocationFk.
   */
  public RowSet getArcFlsLocationsMainLocationFk()
  {
    return (RowSet) getAttributeInternal(ARCFLSLOCATIONSMAINLOCATIONFK);
  }

  /**
   * Gets the view accessor <code>RowSet</code> ArcFlsLocationsRVO.
   */
  public RowSet getArcFlsLocationsRVO()
  {
    return (RowSet) getAttributeInternal(ARCFLSLOCATIONSRVO);
  }
}

