package arc.model.vo;

import arc.model.eo.ArcOldDocumentImpl;

import com.sd.util.db.DBUtil;

import gen.common.GenLib;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 23 10:06:49 GMT+02:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArcOldDocumentViewRowImpl
  extends ViewRowImpl
{


  public static final int ENTITY_ARCOLDDOCUMENT = 0;

  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    OldDocumentPk,
    DocumentNumber,
    DocumentTypeFk,
    DocumentPriorityFk,
    DocumentSecurityFk,
    FromDepartmentFk,
    ToDepartmentFk,
    DocReceiveDate,
    Room,
    Cupboard,
    Shelve,
    Rack,
    DocExpiryDate,
    Keywords,
    OrgCodeFk,
    CreatedBy,
    CreationDate,
    ModifiedBy,
    ModifiedDate,
    UserDepartmentFk,
    DisposedBy,
    DisposalDate,
    OriginalDocumentDisposedFl,
    DisplayDocumentSubject,
    DisplayDocumentDescription,
    DisplayFromDepartmentFk,
    DisplayToDepartmentFk,
    DisplayDocumentTypeFk,
    DisplayDocumentPriorityFk,
    DisplayDocumentSecurityFk,
    DisplayCreatedBy,
    DisplayDisposedBy,
    DisplayDocumentComment,
    DisposedCommitteMembers,
    DisposedDecisionDateG,
    DisposedDecisionDateH,
    DisposedDecisionNo,
    EmployeesFk,
    FilesLocationFk,
    DisplayEmployeesFk,
    DisplayOrgCodeFk,
    DisplayDocumentSubjectSearch,
    DisplayDocumentCommentSearch,
    DisplayDocumentDescriptionSearch,
    DisplayFromDepartmentFkSearch,
    DisplayToDepartmentFkSearch,
    DisplayDocumentTypeFkSearch,
    DisplayDocumentPriorityFkSearch,
    DisplayDocumentSecurityFkSearch,
    DisplayCreatedBySearch,
    DisplayDisposedBySearch,
    DocumentTypeFkSearch,
    DocumentPriorityFkSearch,
    DocumentSecurityFkSearch,
    FromDepartmentFkSearch,
    ToDepartmentFkSearch,
    DisposedFl,
    DisposedCommitteMembersSearch,
    DisplaydisposedCommitteMembers,
    DisplaydisposedDecisionNo,
    DisplaydisposedDecisionDateG,
    EmployeesFkSearch,
    DisplayEmployeesFkSearch,
    DisplayFilesLocationFk,
    DocYear,
    ArcDocumentAttachmentView,
    ArcOldDocumentTlView,
    SsoUsersRVO,
    SsoUsersRVO1,
    SsoActiveLookupValuesDocumentTypeFk,
    SsoActiveLookupValuesDocumentPriorityFk,
    SsoActiveLookupValuesDocumentSecurityFk,
    HcmDepartmentsFrom,
    HcmDepartmentsTO,
    HcmEmployeesRVO,
    ArcFilesLocationRVO;
    private static AttributesEnum[] vals = null;
    ;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int OLDDOCUMENTPK = AttributesEnum.OldDocumentPk.index();
  public static final int DOCUMENTNUMBER = AttributesEnum.DocumentNumber.index();
  public static final int DOCUMENTTYPEFK = AttributesEnum.DocumentTypeFk.index();
  public static final int DOCUMENTPRIORITYFK = AttributesEnum.DocumentPriorityFk.index();
  public static final int DOCUMENTSECURITYFK = AttributesEnum.DocumentSecurityFk.index();
  public static final int FROMDEPARTMENTFK = AttributesEnum.FromDepartmentFk.index();
  public static final int TODEPARTMENTFK = AttributesEnum.ToDepartmentFk.index();
  public static final int DOCRECEIVEDATE = AttributesEnum.DocReceiveDate.index();
  public static final int ROOM = AttributesEnum.Room.index();
  public static final int CUPBOARD = AttributesEnum.Cupboard.index();
  public static final int SHELVE = AttributesEnum.Shelve.index();
  public static final int RACK = AttributesEnum.Rack.index();
  public static final int DOCEXPIRYDATE = AttributesEnum.DocExpiryDate.index();
  public static final int KEYWORDS = AttributesEnum.Keywords.index();
  public static final int ORGCODEFK = AttributesEnum.OrgCodeFk.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
  public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
  public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();
  public static final int DISPOSEDBY = AttributesEnum.DisposedBy.index();
  public static final int DISPOSALDATE = AttributesEnum.DisposalDate.index();
  public static final int ORIGINALDOCUMENTDISPOSEDFL = AttributesEnum.OriginalDocumentDisposedFl.index();
  public static final int DISPLAYDOCUMENTSUBJECT = AttributesEnum.DisplayDocumentSubject.index();
  public static final int DISPLAYDOCUMENTDESCRIPTION = AttributesEnum.DisplayDocumentDescription.index();
  public static final int DISPLAYFROMDEPARTMENTFK = AttributesEnum.DisplayFromDepartmentFk.index();
  public static final int DISPLAYTODEPARTMENTFK = AttributesEnum.DisplayToDepartmentFk.index();
  public static final int DISPLAYDOCUMENTTYPEFK = AttributesEnum.DisplayDocumentTypeFk.index();
  public static final int DISPLAYDOCUMENTPRIORITYFK = AttributesEnum.DisplayDocumentPriorityFk.index();
  public static final int DISPLAYDOCUMENTSECURITYFK = AttributesEnum.DisplayDocumentSecurityFk.index();
  public static final int DISPLAYCREATEDBY = AttributesEnum.DisplayCreatedBy.index();
  public static final int DISPLAYDISPOSEDBY = AttributesEnum.DisplayDisposedBy.index();
  public static final int DISPLAYDOCUMENTCOMMENT = AttributesEnum.DisplayDocumentComment.index();
  public static final int DISPOSEDCOMMITTEMEMBERS = AttributesEnum.DisposedCommitteMembers.index();
  public static final int DISPOSEDDECISIONDATEG = AttributesEnum.DisposedDecisionDateG.index();
  public static final int DISPOSEDDECISIONDATEH = AttributesEnum.DisposedDecisionDateH.index();
  public static final int DISPOSEDDECISIONNO = AttributesEnum.DisposedDecisionNo.index();
  public static final int EMPLOYEESFK = AttributesEnum.EmployeesFk.index();
  public static final int FILESLOCATIONFK = AttributesEnum.FilesLocationFk.index();
  public static final int DISPLAYEMPLOYEESFK = AttributesEnum.DisplayEmployeesFk.index();
  public static final int DISPLAYORGCODEFK = AttributesEnum.DisplayOrgCodeFk.index();
  public static final int DISPLAYDOCUMENTSUBJECTSEARCH = AttributesEnum.DisplayDocumentSubjectSearch.index();
  public static final int DISPLAYDOCUMENTCOMMENTSEARCH = AttributesEnum.DisplayDocumentCommentSearch.index();
  public static final int DISPLAYDOCUMENTDESCRIPTIONSEARCH = AttributesEnum.DisplayDocumentDescriptionSearch.index();
  public static final int DISPLAYFROMDEPARTMENTFKSEARCH = AttributesEnum.DisplayFromDepartmentFkSearch.index();
  public static final int DISPLAYTODEPARTMENTFKSEARCH = AttributesEnum.DisplayToDepartmentFkSearch.index();
  public static final int DISPLAYDOCUMENTTYPEFKSEARCH = AttributesEnum.DisplayDocumentTypeFkSearch.index();
  public static final int DISPLAYDOCUMENTPRIORITYFKSEARCH = AttributesEnum.DisplayDocumentPriorityFkSearch.index();
  public static final int DISPLAYDOCUMENTSECURITYFKSEARCH = AttributesEnum.DisplayDocumentSecurityFkSearch.index();
  public static final int DISPLAYCREATEDBYSEARCH = AttributesEnum.DisplayCreatedBySearch.index();
  public static final int DISPLAYDISPOSEDBYSEARCH = AttributesEnum.DisplayDisposedBySearch.index();
  public static final int DOCUMENTTYPEFKSEARCH = AttributesEnum.DocumentTypeFkSearch.index();
  public static final int DOCUMENTPRIORITYFKSEARCH = AttributesEnum.DocumentPriorityFkSearch.index();
  public static final int DOCUMENTSECURITYFKSEARCH = AttributesEnum.DocumentSecurityFkSearch.index();
  public static final int FROMDEPARTMENTFKSEARCH = AttributesEnum.FromDepartmentFkSearch.index();
  public static final int TODEPARTMENTFKSEARCH = AttributesEnum.ToDepartmentFkSearch.index();
  public static final int DISPOSEDFL = AttributesEnum.DisposedFl.index();
  public static final int DISPOSEDCOMMITTEMEMBERSSEARCH = AttributesEnum.DisposedCommitteMembersSearch.index();
  public static final int DISPLAYDISPOSEDCOMMITTEMEMBERS = AttributesEnum.DisplaydisposedCommitteMembers.index();
  public static final int DISPLAYDISPOSEDDECISIONNO = AttributesEnum.DisplaydisposedDecisionNo.index();
  public static final int DISPLAYDISPOSEDDECISIONDATEG = AttributesEnum.DisplaydisposedDecisionDateG.index();
  public static final int EMPLOYEESFKSEARCH = AttributesEnum.EmployeesFkSearch.index();
  public static final int DISPLAYEMPLOYEESFKSEARCH = AttributesEnum.DisplayEmployeesFkSearch.index();
  public static final int DISPLAYFILESLOCATIONFK = AttributesEnum.DisplayFilesLocationFk.index();
  public static final int DOCYEAR = AttributesEnum.DocYear.index();
  public static final int ARCDOCUMENTATTACHMENTVIEW = AttributesEnum.ArcDocumentAttachmentView.index();
  public static final int ARCOLDDOCUMENTTLVIEW = AttributesEnum.ArcOldDocumentTlView.index();
  public static final int SSOUSERSRVO = AttributesEnum.SsoUsersRVO.index();
  public static final int SSOUSERSRVO1 = AttributesEnum.SsoUsersRVO1.index();
  public static final int SSOACTIVELOOKUPVALUESDOCUMENTTYPEFK =
    AttributesEnum.SsoActiveLookupValuesDocumentTypeFk.index();
  public static final int SSOACTIVELOOKUPVALUESDOCUMENTPRIORITYFK =
    AttributesEnum.SsoActiveLookupValuesDocumentPriorityFk.index();
  public static final int SSOACTIVELOOKUPVALUESDOCUMENTSECURITYFK =
    AttributesEnum.SsoActiveLookupValuesDocumentSecurityFk.index();
  public static final int HCMDEPARTMENTSFROM = AttributesEnum.HcmDepartmentsFrom.index();
  public static final int HCMDEPARTMENTSTO = AttributesEnum.HcmDepartmentsTO.index();
  public static final int HCMEMPLOYEESRVO = AttributesEnum.HcmEmployeesRVO.index();
  public static final int ARCFILESLOCATIONRVO = AttributesEnum.ArcFilesLocationRVO.index();

  /**
   * This is the default constructor (do not remove).
   */
  public ArcOldDocumentViewRowImpl()
  {
  }

  /**
   * Gets ArcOldDocument entity object.
   * @return the ArcOldDocument
   */
  public ArcOldDocumentImpl getArcOldDocument()
  {
    return (ArcOldDocumentImpl) getEntity(ENTITY_ARCOLDDOCUMENT);
  }

  /**
   * Gets the attribute value for OLD_DOCUMENT_PK using the alias name OldDocumentPk.
   * @return the OLD_DOCUMENT_PK
   */
  public BigDecimal getOldDocumentPk()
  {
    return (BigDecimal) getAttributeInternal(OLDDOCUMENTPK);
  }

  /**
   * Sets <code>value</code> as attribute value for OLD_DOCUMENT_PK using the alias name OldDocumentPk.
   * @param value value to set the OLD_DOCUMENT_PK
   */
  public void setOldDocumentPk(BigDecimal value)
  {
    setAttributeInternal(OLDDOCUMENTPK, value);
  }

  /**
   * Gets the attribute value for DOCUMENT_NUMBER using the alias name DocumentNumber.
   * @return the DOCUMENT_NUMBER
   */
  public String getDocumentNumber()
  {
    return (String) getAttributeInternal(DOCUMENTNUMBER);
  }

  /**
   * Sets <code>value</code> as attribute value for DOCUMENT_NUMBER using the alias name DocumentNumber.
   * @param value value to set the DOCUMENT_NUMBER
   */
  public void setDocumentNumber(String value)
  {
    setAttributeInternal(DOCUMENTNUMBER, value);
  }

  /**
   * Gets the attribute value for DOCUMENT_TYPE_FK using the alias name DocumentTypeFk.
   * @return the DOCUMENT_TYPE_FK
   */
  public BigDecimal getDocumentTypeFk()
  {
    return (BigDecimal) getAttributeInternal(DOCUMENTTYPEFK);
  }

  /**
   * Sets <code>value</code> as attribute value for DOCUMENT_TYPE_FK using the alias name DocumentTypeFk.
   * @param value value to set the DOCUMENT_TYPE_FK
   */
  public void setDocumentTypeFk(BigDecimal value)
  {
    setAttributeInternal(DOCUMENTTYPEFK, value);
  }

  /**
   * Gets the attribute value for DOCUMENT_PRIORITY_FK using the alias name DocumentPriorityFk.
   * @return the DOCUMENT_PRIORITY_FK
   */
  public BigDecimal getDocumentPriorityFk()
  {
    return (BigDecimal) getAttributeInternal(DOCUMENTPRIORITYFK);
  }

  /**
   * Sets <code>value</code> as attribute value for DOCUMENT_PRIORITY_FK using the alias name DocumentPriorityFk.
   * @param value value to set the DOCUMENT_PRIORITY_FK
   */
  public void setDocumentPriorityFk(BigDecimal value)
  {
    setAttributeInternal(DOCUMENTPRIORITYFK, value);
  }

  /**
   * Gets the attribute value for DOCUMENT_SECURITY_FK using the alias name DocumentSecurityFk.
   * @return the DOCUMENT_SECURITY_FK
   */
  public BigDecimal getDocumentSecurityFk()
  {
    return (BigDecimal) getAttributeInternal(DOCUMENTSECURITYFK);
  }

  /**
   * Sets <code>value</code> as attribute value for DOCUMENT_SECURITY_FK using the alias name DocumentSecurityFk.
   * @param value value to set the DOCUMENT_SECURITY_FK
   */
  public void setDocumentSecurityFk(BigDecimal value)
  {
    setAttributeInternal(DOCUMENTSECURITYFK, value);
  }

  /**
   * Gets the attribute value for FROM_DEPARTMENT_FK using the alias name FromDepartmentFk.
   * @return the FROM_DEPARTMENT_FK
   */
  public BigDecimal getFromDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(FROMDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as attribute value for FROM_DEPARTMENT_FK using the alias name FromDepartmentFk.
   * @param value value to set the FROM_DEPARTMENT_FK
   */
  public void setFromDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(FROMDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for TO_DEPARTMENT_FK using the alias name ToDepartmentFk.
   * @return the TO_DEPARTMENT_FK
   */
  public BigDecimal getToDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(TODEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as attribute value for TO_DEPARTMENT_FK using the alias name ToDepartmentFk.
   * @param value value to set the TO_DEPARTMENT_FK
   */
  public void setToDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(TODEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for DOC_RECEIVE_DATE using the alias name DocReceiveDate.
   * @return the DOC_RECEIVE_DATE
   */
  public Timestamp getDocReceiveDate()
  {
    return (Timestamp) getAttributeInternal(DOCRECEIVEDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for DOC_RECEIVE_DATE using the alias name DocReceiveDate.
   * @param value value to set the DOC_RECEIVE_DATE
   */
  public void setDocReceiveDate(Timestamp value)
  {
    setAttributeInternal(DOCRECEIVEDATE, value);
  }

  /**
   * Gets the attribute value for ROOM using the alias name Room.
   * @return the ROOM
   */
  public String getRoom()
  {
    return (String) getAttributeInternal(ROOM);
  }

  /**
   * Sets <code>value</code> as attribute value for ROOM using the alias name Room.
   * @param value value to set the ROOM
   */
  public void setRoom(String value)
  {
    setAttributeInternal(ROOM, value);
  }

  /**
   * Gets the attribute value for CUPBOARD using the alias name Cupboard.
   * @return the CUPBOARD
   */
  public String getCupboard()
  {
    return (String) getAttributeInternal(CUPBOARD);
  }

  /**
   * Sets <code>value</code> as attribute value for CUPBOARD using the alias name Cupboard.
   * @param value value to set the CUPBOARD
   */
  public void setCupboard(String value)
  {
    setAttributeInternal(CUPBOARD, value);
  }

  /**
   * Gets the attribute value for SHELVE using the alias name Shelve.
   * @return the SHELVE
   */
  public String getShelve()
  {
    return (String) getAttributeInternal(SHELVE);
  }

  /**
   * Sets <code>value</code> as attribute value for SHELVE using the alias name Shelve.
   * @param value value to set the SHELVE
   */
  public void setShelve(String value)
  {
    setAttributeInternal(SHELVE, value);
  }

  /**
   * Gets the attribute value for RACK using the alias name Rack.
   * @return the RACK
   */
  public String getRack()
  {
    return (String) getAttributeInternal(RACK);
  }

  /**
   * Sets <code>value</code> as attribute value for RACK using the alias name Rack.
   * @param value value to set the RACK
   */
  public void setRack(String value)
  {
    setAttributeInternal(RACK, value);
  }

  /**
   * Gets the attribute value for DOC_EXPIRY_DATE using the alias name DocExpiryDate.
   * @return the DOC_EXPIRY_DATE
   */
  public Timestamp getDocExpiryDate()
  {
    return (Timestamp) getAttributeInternal(DOCEXPIRYDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for DOC_EXPIRY_DATE using the alias name DocExpiryDate.
   * @param value value to set the DOC_EXPIRY_DATE
   */
  public void setDocExpiryDate(Timestamp value)
  {
    setAttributeInternal(DOCEXPIRYDATE, value);
  }

  /**
   * Gets the attribute value for KEYWORDS using the alias name Keywords.
   * @return the KEYWORDS
   */
  public String getKeywords()
  {
    return (String) getAttributeInternal(KEYWORDS);
  }

  /**
   * Sets <code>value</code> as attribute value for KEYWORDS using the alias name Keywords.
   * @param value value to set the KEYWORDS
   */
  public void setKeywords(String value)
  {
    setAttributeInternal(KEYWORDS, value);
  }

  /**
   * Gets the attribute value for ORG_CODE_FK using the alias name OrgCodeFk.
   * @return the ORG_CODE_FK
   */
  public BigDecimal getOrgCodeFk()
  {
    return (BigDecimal) getAttributeInternal(ORGCODEFK);
  }

  /**
   * Sets <code>value</code> as attribute value for ORG_CODE_FK using the alias name OrgCodeFk.
   * @param value value to set the ORG_CODE_FK
   */
  public void setOrgCodeFk(BigDecimal value)
  {
    setAttributeInternal(ORGCODEFK, value);
  }

  /**
   * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
   * @return the CREATED_BY
   */
  public BigDecimal getCreatedBy()
  {
    return (BigDecimal) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
   * @param value value to set the CREATED_BY
   */
  public void setCreatedBy(BigDecimal value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
   * @return the CREATION_DATE
   */
  public Timestamp getCreationDate()
  {
    return (Timestamp) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
   * @param value value to set the CREATION_DATE
   */
  public void setCreationDate(Timestamp value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
   * @return the MODIFIED_BY
   */
  public BigDecimal getModifiedBy()
  {
    return (BigDecimal) getAttributeInternal(MODIFIEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
   * @param value value to set the MODIFIED_BY
   */
  public void setModifiedBy(BigDecimal value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
   * @return the MODIFIED_DATE
   */
  public Timestamp getModifiedDate()
  {
    return (Timestamp) getAttributeInternal(MODIFIEDDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
   * @param value value to set the MODIFIED_DATE
   */
  public void setModifiedDate(Timestamp value)
  {
    setAttributeInternal(MODIFIEDDATE, value);
  }

  /**
   * Gets the attribute value for USER_DEPARTMENT_FK using the alias name UserDepartmentFk.
   * @return the USER_DEPARTMENT_FK
   */
  public BigDecimal getUserDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as attribute value for USER_DEPARTMENT_FK using the alias name UserDepartmentFk.
   * @param value value to set the USER_DEPARTMENT_FK
   */
  public void setUserDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(USERDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for DISPOSED_BY using the alias name DisposedBy.
   * @return the DISPOSED_BY
   */
  public BigDecimal getDisposedBy()
  {
    return (BigDecimal) getAttributeInternal(DISPOSEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for DISPOSED_BY using the alias name DisposedBy.
   * @param value value to set the DISPOSED_BY
   */
  public void setDisposedBy(BigDecimal value)
  {
    setAttributeInternal(DISPOSEDBY, value);
  }

  /**
   * Gets the attribute value for DISPOSAL_DATE using the alias name DisposalDate.
   * @return the DISPOSAL_DATE
   */
  public Timestamp getDisposalDate()
  {
    return (Timestamp) getAttributeInternal(DISPOSALDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for DISPOSAL_DATE using the alias name DisposalDate.
   * @param value value to set the DISPOSAL_DATE
   */
  public void setDisposalDate(Timestamp value)
  {
    setAttributeInternal(DISPOSALDATE, value);
  }

  /**
   * Gets the attribute value for ORIGINAL_DOCUMENT_DISPOSED_FL using the alias name OriginalDocumentDisposedFl.
   * @return the ORIGINAL_DOCUMENT_DISPOSED_FL
   */
  public BigDecimal getOriginalDocumentDisposedFl()
  {
    return (BigDecimal) getAttributeInternal(ORIGINALDOCUMENTDISPOSEDFL);
  }

  /**
   * Sets <code>value</code> as attribute value for ORIGINAL_DOCUMENT_DISPOSED_FL using the alias name OriginalDocumentDisposedFl.
   * @param value value to set the ORIGINAL_DOCUMENT_DISPOSED_FL
   */
  public void setOriginalDocumentDisposedFl(BigDecimal value)
  {
    setAttributeInternal(ORIGINALDOCUMENTDISPOSEDFL, value);
  }

  /**
   * Gets the attribute value for DISPLAY_DOCUMENT_SUBJECT using the alias name DisplayDocumentSubject.
   * @return the DISPLAY_DOCUMENT_SUBJECT
   */
  public String getDisplayDocumentSubject()
  {
    return (String) getAttributeInternal(DISPLAYDOCUMENTSUBJECT);
  }

  /**
   * Sets <code>value</code> as attribute value for DISPLAY_DOCUMENT_SUBJECT using the alias name DisplayDocumentSubject.
   * @param value value to set the DISPLAY_DOCUMENT_SUBJECT
   */
  public void setDisplayDocumentSubject(String value)
  {
    setAttributeInternal(DISPLAYDOCUMENTSUBJECT, value);
  }


  /**
   * Gets the attribute value for DISPLAY_DOCUMENT_DESCRIPTION using the alias name DisplayDocumentDescription.
   * @return the DISPLAY_DOCUMENT_DESCRIPTION
   */
  public String getDisplayDocumentDescription()
  {
    return (String) getAttributeInternal(DISPLAYDOCUMENTDESCRIPTION);
  }

  /**
   * Sets <code>value</code> as attribute value for DISPLAY_DOCUMENT_DESCRIPTION using the alias name DisplayDocumentDescription.
   * @param value value to set the DISPLAY_DOCUMENT_DESCRIPTION
   */
  public void setDisplayDocumentDescription(String value)
  {
    setAttributeInternal(DISPLAYDOCUMENTDESCRIPTION, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayFromDepartmentFk.
   * @return the DisplayFromDepartmentFk
   */
  public String getDisplayFromDepartmentFk()
  {
    return (String) getAttributeInternal(DISPLAYFROMDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayFromDepartmentFk.
   * @param value value to set the  DisplayFromDepartmentFk
   */
  public void setDisplayFromDepartmentFk(String value)
  {
    setAttributeInternal(DISPLAYFROMDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayToDepartmentFk.
   * @return the DisplayToDepartmentFk
   */
  public String getDisplayToDepartmentFk()
  {
    return (String) getAttributeInternal(DISPLAYTODEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayToDepartmentFk.
   * @param value value to set the  DisplayToDepartmentFk
   */
  public void setDisplayToDepartmentFk(String value)
  {
    setAttributeInternal(DISPLAYTODEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayOrgCodeFk.
   * @return the DisplayOrgCodeFk
   */
  public String getDisplayOrgCodeFk()
  {
    return (String) getAttributeInternal(DISPLAYORGCODEFK);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDocumentTypeFk.
   * @return the DisplayDocumentTypeFk
   */
  public String getDisplayDocumentTypeFk()
  {
    return (String) getAttributeInternal(DISPLAYDOCUMENTTYPEFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDocumentTypeFk.
   * @param value value to set the  DisplayDocumentTypeFk
   */
  public void setDisplayDocumentTypeFk(String value)
  {
    setAttributeInternal(DISPLAYDOCUMENTTYPEFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDocumentPriorityFk.
   * @return the DisplayDocumentPriorityFk
   */
  public String getDisplayDocumentPriorityFk()
  {
    return (String) getAttributeInternal(DISPLAYDOCUMENTPRIORITYFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDocumentPriorityFk.
   * @param value value to set the  DisplayDocumentPriorityFk
   */
  public void setDisplayDocumentPriorityFk(String value)
  {
    setAttributeInternal(DISPLAYDOCUMENTPRIORITYFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDocumentSecurityFk.
   * @return the DisplayDocumentSecurityFk
   */
  public String getDisplayDocumentSecurityFk()
  {
    return (String) getAttributeInternal(DISPLAYDOCUMENTSECURITYFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDocumentSecurityFk.
   * @param value value to set the  DisplayDocumentSecurityFk
   */
  public void setDisplayDocumentSecurityFk(String value)
  {
    setAttributeInternal(DISPLAYDOCUMENTSECURITYFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayCreatedBy.
   * @return the DisplayCreatedBy
   */
  public String getDisplayCreatedBy()
  {
    return (String) getAttributeInternal(DISPLAYCREATEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayCreatedBy.
   * @param value value to set the  DisplayCreatedBy
   */
  public void setDisplayCreatedBy(String value)
  {
    setAttributeInternal(DISPLAYCREATEDBY, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDisposedBy.
   * @return the DisplayDisposedBy
   */
  public String getDisplayDisposedBy()
  {
    return (String) getAttributeInternal(DISPLAYDISPOSEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDisposedBy.
   * @param value value to set the  DisplayDisposedBy
   */
  public void setDisplayDisposedBy(String value)
  {
    setAttributeInternal(DISPLAYDISPOSEDBY, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDocumentSubjectSearch.
   * @return the DisplayDocumentSubjectSearch
   */
  public String getDisplayDocumentSubjectSearch()
  {
    return (String) getAttributeInternal(DISPLAYDOCUMENTSUBJECT);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDocumentSubjectSearch.
   * @param value value to set the  DisplayDocumentSubjectSearch
   */
  public void setDisplayDocumentSubjectSearch(String value)
  {
    setAttributeInternal(DISPLAYDOCUMENTSUBJECT, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDocumentCommentSearch.
   * @return the DisplayDocumentCommentSearch
   */
  public String getDisplayDocumentCommentSearch()
  {
    return (String) getAttributeInternal(DISPLAYDOCUMENTCOMMENT);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDocumentCommentSearch.
   * @param value value to set the  DisplayDocumentCommentSearch
   */
  public void setDisplayDocumentCommentSearch(String value)
  {
    setAttributeInternal(DISPLAYDOCUMENTCOMMENT, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDocumentDescriptionSearch.
   * @return the DisplayDocumentDescriptionSearch
   */
  public String getDisplayDocumentDescriptionSearch()
  {
    return (String) getAttributeInternal(DISPLAYDOCUMENTDESCRIPTION);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDocumentDescriptionSearch.
   * @param value value to set the  DisplayDocumentDescriptionSearch
   */
  public void setDisplayDocumentDescriptionSearch(String value)
  {
    setAttributeInternal(DISPLAYDOCUMENTDESCRIPTION, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayFromDepartmentFkSearch.
   * @return the DisplayFromDepartmentFkSearch
   */
  public String getDisplayFromDepartmentFkSearch()
  {
    return (String) getAttributeInternal(DISPLAYFROMDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayFromDepartmentFkSearch.
   * @param value value to set the  DisplayFromDepartmentFkSearch
   */
  public void setDisplayFromDepartmentFkSearch(String value)
  {
    setAttributeInternal(DISPLAYFROMDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayToDepartmentFkSearch.
   * @return the DisplayToDepartmentFkSearch
   */
  public String getDisplayToDepartmentFkSearch()
  {
    return (String) getAttributeInternal(DISPLAYTODEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayToDepartmentFkSearch.
   * @param value value to set the  DisplayToDepartmentFkSearch
   */
  public void setDisplayToDepartmentFkSearch(String value)
  {
    setAttributeInternal(DISPLAYTODEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDocumentTypeFkSearch.
   * @return the DisplayDocumentTypeFkSearch
   */
  public String getDisplayDocumentTypeFkSearch()
  {
    return (String) getAttributeInternal(DISPLAYDOCUMENTTYPEFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDocumentTypeFkSearch.
   * @param value value to set the  DisplayDocumentTypeFkSearch
   */
  public void setDisplayDocumentTypeFkSearch(String value)
  {
    setAttributeInternal(DISPLAYDOCUMENTTYPEFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDocumentPriorityFkSearch.
   * @return the DisplayDocumentPriorityFkSearch
   */
  public String getDisplayDocumentPriorityFkSearch()
  {
    return (String) getAttributeInternal(DISPLAYDOCUMENTPRIORITYFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDocumentPriorityFkSearch.
   * @param value value to set the  DisplayDocumentPriorityFkSearch
   */
  public void setDisplayDocumentPriorityFkSearch(String value)
  {
    setAttributeInternal(DISPLAYDOCUMENTPRIORITYFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDocumentSecurityFkSearch.
   * @return the DisplayDocumentSecurityFkSearch
   */
  public String getDisplayDocumentSecurityFkSearch()
  {
    return (String) getAttributeInternal(DISPLAYDOCUMENTSECURITYFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDocumentSecurityFkSearch.
   * @param value value to set the  DisplayDocumentSecurityFkSearch
   */
  public void setDisplayDocumentSecurityFkSearch(String value)
  {
    setAttributeInternal(DISPLAYDOCUMENTSECURITYFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayCreatedBySearch.
   * @return the DisplayCreatedBySearch
   */
  public String getDisplayCreatedBySearch()
  {
    return (String) getAttributeInternal(DISPLAYCREATEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayCreatedBySearch.
   * @param value value to set the  DisplayCreatedBySearch
   */
  public void setDisplayCreatedBySearch(String value)
  {
    setAttributeInternal(DISPLAYCREATEDBY, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDisposedBySearch.
   * @return the DisplayDisposedBySearch
   */
  public String getDisplayDisposedBySearch()
  {
    return (String) getAttributeInternal(DISPLAYDISPOSEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDisposedBySearch.
   * @param value value to set the  DisplayDisposedBySearch
   */
  public void setDisplayDisposedBySearch(String value)
  {
    setAttributeInternal(DISPLAYDISPOSEDBY, value);
  }


  /**
   * Gets the attribute value for the calculated attribute DisplayDocumentComment.
   * @return the DisplayDocumentComment
   */
  public String getDisplayDocumentComment()
  {
    return (String) getAttributeInternal(DISPLAYDOCUMENTCOMMENT);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDocumentComment.
   * @param value value to set the  DisplayDocumentComment
   */
  public void setDisplayDocumentComment(String value)
  {
    setAttributeInternal(DISPLAYDOCUMENTCOMMENT, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DocumentTypeFkSearch.
   * @return the DocumentTypeFkSearch
   */
  public BigDecimal getDocumentTypeFkSearch()
  {
    return (BigDecimal) getAttributeInternal(DOCUMENTTYPEFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DocumentTypeFkSearch.
   * @param value value to set the  DocumentTypeFkSearch
   */
  public void setDocumentTypeFkSearch(BigDecimal value)
  {
    setAttributeInternal(DOCUMENTTYPEFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DocumentPriorityFkSearch.
   * @return the DocumentPriorityFkSearch
   */
  public BigDecimal getDocumentPriorityFkSearch()
  {
    return (BigDecimal) getAttributeInternal(DOCUMENTPRIORITYFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DocumentPriorityFkSearch.
   * @param value value to set the  DocumentPriorityFkSearch
   */
  public void setDocumentPriorityFkSearch(BigDecimal value)
  {
    setAttributeInternal(DOCUMENTPRIORITYFKSEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DocumentSecurityFkSearch.
   * @return the DocumentSecurityFkSearch
   */
  public BigDecimal getDocumentSecurityFkSearch()
  {
    return (BigDecimal) getAttributeInternal(DOCUMENTSECURITYFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DocumentSecurityFkSearch.
   * @param value value to set the  DocumentSecurityFkSearch
   */
  public void setDocumentSecurityFkSearch(BigDecimal value)
  {
    setAttributeInternal(DOCUMENTSECURITYFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute FromDepartmentFkSearch.
   * @return the FromDepartmentFkSearch
   */
  public BigDecimal getFromDepartmentFkSearch()
  {
    return (BigDecimal) getAttributeInternal(FROMDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute FromDepartmentFkSearch.
   * @param value value to set the  FromDepartmentFkSearch
   */
  public void setFromDepartmentFkSearch(BigDecimal value)
  {
    setAttributeInternal(FROMDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute ToDepartmentFkSearch.
   * @return the ToDepartmentFkSearch
   */
  public BigDecimal getToDepartmentFkSearch()
  {
    return (BigDecimal) getAttributeInternal(TODEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute ToDepartmentFkSearch.
   * @param value value to set the  ToDepartmentFkSearch
   */
  public void setToDepartmentFkSearch(BigDecimal value)
  {
    setAttributeInternal(TODEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for DISPOSED_COMMITTE_MEMBERS using the alias name DisposedCommitteMembers.
   * @return the DISPOSED_COMMITTE_MEMBERS
   */
  public String getDisposedCommitteMembers()
  {
    return (String) getAttributeInternal(DISPOSEDCOMMITTEMEMBERS);
  }

  /**
   * Sets <code>value</code> as attribute value for DISPOSED_COMMITTE_MEMBERS using the alias name DisposedCommitteMembers.
   * @param value value to set the DISPOSED_COMMITTE_MEMBERS
   */
  public void setDisposedCommitteMembers(String value)
  {
    setAttributeInternal(DISPOSEDCOMMITTEMEMBERS, value);
  }

  /**
   * Gets the attribute value for DISPOSED_DECISION_DATE_G using the alias name DisposedDecisionDateG.
   * @return the DISPOSED_DECISION_DATE_G
   */
  public Timestamp getDisposedDecisionDateG()
  {
    return (Timestamp) getAttributeInternal(DISPOSEDDECISIONDATEG);
  }

  /**
   * Sets <code>value</code> as attribute value for DISPOSED_DECISION_DATE_G using the alias name DisposedDecisionDateG.
   * @param value value to set the DISPOSED_DECISION_DATE_G
   */
  public void setDisposedDecisionDateG(Timestamp value)
  {
    setAttributeInternal(DISPOSEDDECISIONDATEG, value);
  }

  /**
   * Gets the attribute value for DISPOSED_DECISION_DATE_H using the alias name DisposedDecisionDateH.
   * @return the DISPOSED_DECISION_DATE_H
   */
  public BigDecimal getDisposedDecisionDateH()
  {
    return (BigDecimal) getAttributeInternal(DISPOSEDDECISIONDATEH);
  }

  /**
   * Sets <code>value</code> as attribute value for DISPOSED_DECISION_DATE_H using the alias name DisposedDecisionDateH.
   * @param value value to set the DISPOSED_DECISION_DATE_H
   */
  public void setDisposedDecisionDateH(BigDecimal value)
  {
    setAttributeInternal(DISPOSEDDECISIONDATEH, value);
  }

  /**
   * Gets the attribute value for DISPOSED_DECISION_NO using the alias name DisposedDecisionNo.
   * @return the DISPOSED_DECISION_NO
   */
  public BigDecimal getDisposedDecisionNo()
  {
    return (BigDecimal) getAttributeInternal(DISPOSEDDECISIONNO);
  }

  /**
   * Sets <code>value</code> as attribute value for DISPOSED_DECISION_NO using the alias name DisposedDecisionNo.
   * @param value value to set the DISPOSED_DECISION_NO
   */
  public void setDisposedDecisionNo(BigDecimal value)
  {
    setAttributeInternal(DISPOSEDDECISIONNO, value);
  }


  /**
   * Gets the attribute value for the calculated attribute DisposedFl.
   * @return the DisposedFl
   */
  public BigDecimal getDisposedFl()
  {
    return (BigDecimal) getAttributeInternal(DISPOSEDFL);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisposedFl.
   * @param value value to set the  DisposedFl
   */
  public void setDisposedFl(BigDecimal value)
  {
    setAttributeInternal(DISPOSEDFL, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisposedCommitteMembersSearch.
   * @return the DisposedCommitteMembersSearch
   */
  public String getDisposedCommitteMembersSearch()
  {
    return (String) getAttributeInternal(DISPOSEDCOMMITTEMEMBERS);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisposedCommitteMembersSearch.
   * @param value value to set the  DisposedCommitteMembersSearch
   */
  public void setDisposedCommitteMembersSearch(String value)
  {
    setAttributeInternal(DISPOSEDCOMMITTEMEMBERSSEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplaydisposedCommitteMembers.
   * @return the DisplaydisposedCommitteMembers
   */
  public String getDisplaydisposedCommitteMembers()
  {
    return (String) getAttributeInternal(DISPLAYDISPOSEDCOMMITTEMEMBERS);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplaydisposedCommitteMembers.
   * @param value value to set the  DisplaydisposedCommitteMembers
   */
  public void setDisplaydisposedCommitteMembers(String value)
  {
    setAttributeInternal(DISPLAYDISPOSEDCOMMITTEMEMBERS, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplaydisposedDecisionNo.
   * @return the DisplaydisposedDecisionNo
   */
  public BigDecimal getDisplaydisposedDecisionNo()
  {
    return (BigDecimal) getAttributeInternal(DISPLAYDISPOSEDDECISIONNO);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplaydisposedDecisionNo.
   * @param value value to set the  DisplaydisposedDecisionNo
   */
  public void setDisplaydisposedDecisionNo(BigDecimal value)
  {
    setAttributeInternal(DISPLAYDISPOSEDDECISIONNO, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplaydisposedDecisionDateG.
   * @return the DisplaydisposedDecisionDateG
   */
  public Timestamp getDisplaydisposedDecisionDateG()
  {
    return (Timestamp) getAttributeInternal(DISPLAYDISPOSEDDECISIONDATEG);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplaydisposedDecisionDateG.
   * @param value value to set the  DisplaydisposedDecisionDateG
   */
  public void setDisplaydisposedDecisionDateG(Timestamp value)
  {
    setAttributeInternal(DISPLAYDISPOSEDDECISIONDATEG, value);
  }

  /**
   * Gets the attribute value for EMPLOYEES_FK using the alias name EmployeesFk.
   * @return the EMPLOYEES_FK
   */
  public BigDecimal getEmployeesFk()
  {
    return (BigDecimal) getAttributeInternal(EMPLOYEESFK);
  }

  /**
   * Sets <code>value</code> as attribute value for EMPLOYEES_FK using the alias name EmployeesFk.
   * @param value value to set the EMPLOYEES_FK
   */
  public void setEmployeesFk(BigDecimal value)
  {
    setAttributeInternal(EMPLOYEESFK, value);
  }

  /**
   * Gets the attribute value for FILES_LOCATION_FK using the alias name FilesLocationFk.
   * @return the FILES_LOCATION_FK
   */
  public BigDecimal getFilesLocationFk()
  {
    return (BigDecimal) getAttributeInternal(FILESLOCATIONFK);
  }

  /**
   * Sets <code>value</code> as attribute value for FILES_LOCATION_FK using the alias name FilesLocationFk.
   * @param value value to set the FILES_LOCATION_FK
   */
  public void setFilesLocationFk(BigDecimal value)
  {
    setAttributeInternal(FILESLOCATIONFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute EmployeesFkSearch.
   * @return the EmployeesFkSearch
   */
  public BigDecimal getEmployeesFkSearch()
  {
    return (BigDecimal) getAttributeInternal(EMPLOYEESFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute EmployeesFkSearch.
   * @param value value to set the  EmployeesFkSearch
   */
  public void setEmployeesFkSearch(BigDecimal value)
  {
    setAttributeInternal(EMPLOYEESFKSEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayEmployeesFk.
   * @return the DisplayEmployeesFk
   */
  public String getDisplayEmployeesFk()
  {
    return (String) getAttributeInternal(DISPLAYEMPLOYEESFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayEmployeesFk.
   * @param value value to set the  DisplayEmployeesFk
   */
  public void setDisplayEmployeesFk(String value)
  {
    setAttributeInternal(DISPLAYEMPLOYEESFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayEmployeesFkSearch.
   * @return the DisplayEmployeesFkSearch
   */
  public String getDisplayEmployeesFkSearch()
  {
    return (String) getAttributeInternal(DISPLAYEMPLOYEESFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayEmployeesFkSearch.
   * @param value value to set the  DisplayEmployeesFkSearch
   */
  public void setDisplayEmployeesFkSearch(String value)
  {
    setAttributeInternal(DISPLAYEMPLOYEESFKSEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayFilesLocationFk.
   * @return the DisplayFilesLocationFk
   */
  public String getDisplayFilesLocationFk()
  {
    return (String) getAttributeInternal(DISPLAYFILESLOCATIONFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayFilesLocationFk.
   * @param value value to set the  DisplayFilesLocationFk
   */
  public void setDisplayFilesLocationFk(String value)
  {
    setAttributeInternal(DISPLAYFILESLOCATIONFK, value);
  }

  /**
   * Gets the attribute value for DOC_YEAR using the alias name DocYear.
   * @return the DOC_YEAR
   */
  public BigDecimal getDocYear()
  {
    return (BigDecimal) getAttributeInternal(DOCYEAR);
  }

  /**
   * Sets <code>value</code> as attribute value for DOC_YEAR using the alias name DocYear.
   * @param value value to set the DOC_YEAR
   */
  public void setDocYear(BigDecimal value)
  {
    setAttributeInternal(DOCYEAR, value);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link ArcDocumentAttachmentView.
   */
  public RowIterator getArcDocumentAttachmentView()
  {
    return (RowIterator) getAttributeInternal(ARCDOCUMENTATTACHMENTVIEW);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link ArcOldDocumentTlView.
   */
  public RowIterator getArcOldDocumentTlView()
  {
    return (RowIterator) getAttributeInternal(ARCOLDDOCUMENTTLVIEW);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link SsoUsersRVO.
   */
  public RowIterator getSsoUsersRVO()
  {
    return (RowIterator) getAttributeInternal(SSOUSERSRVO);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link SsoUsersRVO1.
   */
  public RowIterator getSsoUsersRVO1()
  {
    return (RowIterator) getAttributeInternal(SSOUSERSRVO1);
  }

  /**
   * Gets the view accessor <code>RowSet</code> SsoActiveLookupValuesDocumentTypeFk.
   */
  public RowSet getSsoActiveLookupValuesDocumentTypeFk()
  {
    return (RowSet) getAttributeInternal(SSOACTIVELOOKUPVALUESDOCUMENTTYPEFK);
  }

  /**
   * Gets the view accessor <code>RowSet</code> SsoActiveLookupValuesDocumentPriorityFk.
   */
  public RowSet getSsoActiveLookupValuesDocumentPriorityFk()
  {
    return (RowSet) getAttributeInternal(SSOACTIVELOOKUPVALUESDOCUMENTPRIORITYFK);
  }

  /**
   * Gets the view accessor <code>RowSet</code> SsoActiveLookupValuesDocumentSecurityFk.
   */
  public RowSet getSsoActiveLookupValuesDocumentSecurityFk()
  {
    return (RowSet) getAttributeInternal(SSOACTIVELOOKUPVALUESDOCUMENTSECURITYFK);
  }

  /**
   * Gets the view accessor <code>RowSet</code> HcmDepartmentsFrom.
   */
  public RowSet getHcmDepartmentsFrom()
  {
    return (RowSet) getAttributeInternal(HCMDEPARTMENTSFROM);
  }

  /**
   * Gets the view accessor <code>RowSet</code> HcmDepartmentsTO.
   */
  public RowSet getHcmDepartmentsTO()
  {
    return (RowSet) getAttributeInternal(HCMDEPARTMENTSTO);
  }

  /**
   * Gets the view accessor <code>RowSet</code> HcmEmployeesRVO.
   */
  public RowSet getHcmEmployeesRVO()
  {
    return (RowSet) getAttributeInternal(HCMEMPLOYEESRVO);
  }

  /**
   * Gets the view accessor <code>RowSet</code> ArcFilesLocationRVO.
   */
  public RowSet getArcFilesLocationRVO()
  {
    return (RowSet) getAttributeInternal(ARCFILESLOCATIONRVO);
  }
}

